enum ActivationFunction {
    ReLU,
    Sigmoid,
    Tanh,
    None,
};

__kernel void cnn2dFilter(
    __global float* input,
    const int channels,
    const int width,
    const int height,

    __global float* filterWeights,
    const float filterBias,
    const int filterSize,

    __global float* output,
    const int activation
) {
    const int x = get_global_id(0);
    const int y = get_global_id(1);

    const int pad = filterSize / 2;
    float sum = 0.0f;

    for (int j = 0; j < filterSize; j++) {
        int iy = y + j - pad;
        if (iy < 0 || iy >= height) continue;
        for (int i = 0; i < filterSize; i++) {
            int ix = x + i - pad;
            if (ix < 0 || ix >= width) continue;
            for (int k = 0; k < channels; k++) {
                sum += input[iy * width * channels + ix * channels + k]
                     * filterWeights[j * filterSize * channels + i * channels + k];
            }
        }
    }

    sum += filterBias;

    switch (activation) {
        case ReLU:    output[y * width + x] = max(sum, 0.0f); break;
        case Sigmoid: output[y * width + x] = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    output[y * width + x] = tanh(sum); break;
        case None:    output[y * width + x] = sum; break;
    }
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w64_h64_c3_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// params: input, filterWeights, filterBias, output, activation, accumulate
// width=64 height=64 channels=3 filterSize=3
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w64_h64_c3_f3(
    __global const float* input,
    __global const float* filterWeights,
    const float filterBias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 64 || y >= 64) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 192 + (x - 1) * 3;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 192 + x * 3;
        sum += input[base_0_1] * filterWeights[3];
        sum += input[base_0_1 + 1] * filterWeights[4];
        sum += input[base_0_1 + 2] * filterWeights[5];
    }

    // tap (0, 2)
    if (y >= 1 && x < 63)
    {
        const int base_0_2 = (y - 1) * 192 + (x + 1) * 3;
        sum += input[base_0_2] * filterWeights[6];
        sum += input[base_0_2 + 1] * filterWeights[7];
        sum += input[base_0_2 + 2] * filterWeights[8];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 192 + (x - 1) * 3;
        sum += input[base_1_0] * filterWeights[9];
        sum += input[base_1_0 + 1] * filterWeights[10];
        sum += input[base_1_0 + 2] * filterWeights[11];
    }

    // tap (1, 1)
    const int base_1_1 = y * 192 + x * 3;
    sum += input[base_1_1] * filterWeights[12];
    sum += input[base_1_1 + 1] * filterWeights[13];
    sum += input[base_1_1 + 2] * filterWeights[14];

    // tap (1, 2)
    if (x < 63)
    {
        const int base_1_2 = y * 192 + (x + 1) * 3;
        sum += input[base_1_2] * filterWeights[15];
        sum += input[base_1_2 + 1] * filterWeights[16];
        sum += input[base_1_2 + 2] * filterWeights[17];
    }

    // tap (2, 0)
    if (y < 63 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 192 + (x - 1) * 3;
        sum += input[base_2_0] * filterWeights[18];
        sum += input[base_2_0 + 1] * filterWeights[19];
        sum += input[base_2_0 + 2] * filterWeights[20];
    }

    // tap (2, 1)
    if (y < 63)
    {
        const int base_2_1 = (y + 1) * 192 + x * 3;
        sum += input[base_2_1] * filterWeights[21];
        sum += input[base_2_1 + 1] * filterWeights[22];
        sum += input[base_2_1 + 2] * filterWeights[23];
    }

    // tap (2, 2)
    if (y < 63 && x < 63)
    {
        const int base_2_2 = (y + 1) * 192 + (x + 1) * 3;
        sum += input[base_2_2] * filterWeights[24];
        sum += input[base_2_2 + 1] * filterWeights[25];
        sum += input[base_2_2 + 2] * filterWeights[26];
    }

    sum += filterBias;

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 64 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3
// params: input, filterWeights, filterBias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    const float filterBias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
        sum += input[base_0_0] * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 28 + x * 1;
        sum += input[base_0_1] * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
        sum += input[base_0_2] * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 28 + (x - 1) * 1;
        sum += input[base_1_0] * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 28 + x * 1;
    sum += input[base_1_1] * filterWeights[4];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 28 + (x + 1) * 1;
        sum += input[base_1_2] * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
        sum += input[base_2_0] * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 28 + x * 1;
        sum += input[base_2_1] * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
        sum += input[base_2_2] * filterWeights[8];
    }

    sum += filterBias;

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c4_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=4 filterSize=3
// params: input, filterWeights, filterBias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c4_f3(
    __global const float* input,
    __global const float* filterWeights,
    const float filterBias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 112 + (x - 1) * 4;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
        sum += input[base_0_0 + 3] * filterWeights[3];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 112 + x * 4;
        sum += input[base_0_1] * filterWeights[4];
        sum += input[base_0_1 + 1] * filterWeights[5];
        sum += input[base_0_1 + 2] * filterWeights[6];
        sum += input[base_0_1 + 3] * filterWeights[7];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 112 + (x + 1) * 4;
        sum += input[base_0_2] * filterWeights[8];
        sum += input[base_0_2 + 1] * filterWeights[9];
        sum += input[base_0_2 + 2] * filterWeights[10];
        sum += input[base_0_2 + 3] * filterWeights[11];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 112 + (x - 1) * 4;
        sum += input[base_1_0] * filterWeights[12];
        sum += input[base_1_0 + 1] * filterWeights[13];
        sum += input[base_1_0 + 2] * filterWeights[14];
        sum += input[base_1_0 + 3] * filterWeights[15];
    }

    // tap (1, 1)
    const int base_1_1 = y * 112 + x * 4;
    sum += input[base_1_1] * filterWeights[16];
    sum += input[base_1_1 + 1] * filterWeights[17];
    sum += input[base_1_1 + 2] * filterWeights[18];
    sum += input[base_1_1 + 3] * filterWeights[19];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 112 + (x + 1) * 4;
        sum += input[base_1_2] * filterWeights[20];
        sum += input[base_1_2 + 1] * filterWeights[21];
        sum += input[base_1_2 + 2] * filterWeights[22];
        sum += input[base_1_2 + 3] * filterWeights[23];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 112 + (x - 1) * 4;
        sum += input[base_2_0] * filterWeights[24];
        sum += input[base_2_0 + 1] * filterWeights[25];
        sum += input[base_2_0 + 2] * filterWeights[26];
        sum += input[base_2_0 + 3] * filterWeights[27];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 112 + x * 4;
        sum += input[base_2_1] * filterWeights[28];
        sum += input[base_2_1 + 1] * filterWeights[29];
        sum += input[base_2_1 + 2] * filterWeights[30];
        sum += input[base_2_1 + 3] * filterWeights[31];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 112 + (x + 1) * 4;
        sum += input[base_2_2] * filterWeights[32];
        sum += input[base_2_2 + 1] * filterWeights[33];
        sum += input[base_2_2 + 2] * filterWeights[34];
        sum += input[base_2_2 + 3] * filterWeights[35];
    }

    sum += filterBias;

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c8_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=8 filterSize=3
// params: input, filterWeights, filterBias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c8_f3(
    __global const float* input,
    __global const float* filterWeights,
    const float filterBias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 224 + (x - 1) * 8;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
        sum += input[base_0_0 + 3] * filterWeights[3];
        sum += input[base_0_0 + 4] * filterWeights[4];
        sum += input[base_0_0 + 5] * filterWeights[5];
        sum += input[base_0_0 + 6] * filterWeights[6];
        sum += input[base_0_0 + 7] * filterWeights[7];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 224 + x * 8;
        sum += input[base_0_1] * filterWeights[8];
        sum += input[base_0_1 + 1] * filterWeights[9];
        sum += input[base_0_1 + 2] * filterWeights[10];
        sum += input[base_0_1 + 3] * filterWeights[11];
        sum += input[base_0_1 + 4] * filterWeights[12];
        sum += input[base_0_1 + 5] * filterWeights[13];
        sum += input[base_0_1 + 6] * filterWeights[14];
        sum += input[base_0_1 + 7] * filterWeights[15];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 224 + (x + 1) * 8;
        sum += input[base_0_2] * filterWeights[16];
        sum += input[base_0_2 + 1] * filterWeights[17];
        sum += input[base_0_2 + 2] * filterWeights[18];
        sum += input[base_0_2 + 3] * filterWeights[19];
        sum += input[base_0_2 + 4] * filterWeights[20];
        sum += input[base_0_2 + 5] * filterWeights[21];
        sum += input[base_0_2 + 6] * filterWeights[22];
        sum += input[base_0_2 + 7] * filterWeights[23];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 224 + (x - 1) * 8;
        sum += input[base_1_0] * filterWeights[24];
        sum += input[base_1_0 + 1] * filterWeights[25];
        sum += input[base_1_0 + 2] * filterWeights[26];
        sum += input[base_1_0 + 3] * filterWeights[27];
        sum += input[base_1_0 + 4] * filterWeights[28];
        sum += input[base_1_0 + 5] * filterWeights[29];
        sum += input[base_1_0 + 6] * filterWeights[30];
        sum += input[base_1_0 + 7] * filterWeights[31];
    }

    // tap (1, 1)
    const int base_1_1 = y * 224 + x * 8;
    sum += input[base_1_1] * filterWeights[32];
    sum += input[base_1_1 + 1] * filterWeights[33];
    sum += input[base_1_1 + 2] * filterWeights[34];
    sum += input[base_1_1 + 3] * filterWeights[35];
    sum += input[base_1_1 + 4] * filterWeights[36];
    sum += input[base_1_1 + 5] * filterWeights[37];
    sum += input[base_1_1 + 6] * filterWeights[38];
    sum += input[base_1_1 + 7] * filterWeights[39];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 224 + (x + 1) * 8;
        sum += input[base_1_2] * filterWeights[40];
        sum += input[base_1_2 + 1] * filterWeights[41];
        sum += input[base_1_2 + 2] * filterWeights[42];
        sum += input[base_1_2 + 3] * filterWeights[43];
        sum += input[base_1_2 + 4] * filterWeights[44];
        sum += input[base_1_2 + 5] * filterWeights[45];
        sum += input[base_1_2 + 6] * filterWeights[46];
        sum += input[base_1_2 + 7] * filterWeights[47];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 224 + (x - 1) * 8;
        sum += input[base_2_0] * filterWeights[48];
        sum += input[base_2_0 + 1] * filterWeights[49];
        sum += input[base_2_0 + 2] * filterWeights[50];
        sum += input[base_2_0 + 3] * filterWeights[51];
        sum += input[base_2_0 + 4] * filterWeights[52];
        sum += input[base_2_0 + 5] * filterWeights[53];
        sum += input[base_2_0 + 6] * filterWeights[54];
        sum += input[base_2_0 + 7] * filterWeights[55];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 224 + x * 8;
        sum += input[base_2_1] * filterWeights[56];
        sum += input[base_2_1 + 1] * filterWeights[57];
        sum += input[base_2_1 + 2] * filterWeights[58];
        sum += input[base_2_1 + 3] * filterWeights[59];
        sum += input[base_2_1 + 4] * filterWeights[60];
        sum += input[base_2_1 + 5] * filterWeights[61];
        sum += input[base_2_1 + 6] * filterWeights[62];
        sum += input[base_2_1 + 7] * filterWeights[63];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 224 + (x + 1) * 8;
        sum += input[base_2_2] * filterWeights[64];
        sum += input[base_2_2 + 1] * filterWeights[65];
        sum += input[base_2_2 + 2] * filterWeights[66];
        sum += input[base_2_2 + 3] * filterWeights[67];
        sum += input[base_2_2 + 4] * filterWeights[68];
        sum += input[base_2_2 + 5] * filterWeights[69];
        sum += input[base_2_2 + 6] * filterWeights[70];
        sum += input[base_2_2 + 7] * filterWeights[71];
    }

    sum += filterBias;

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=1 poolSize=2 -> 14x14
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 28]);
    m0 = max(m0, input[base + 29]);
    output[(oy * 14 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dDense_i196_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=196 outputFloats=10
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i196_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 196; i++)
        sum += input[i] * weights[o * 196 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c8_p4 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=8 poolSize=4 -> 7x7
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c8_p4(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 4) * 28 + (ox * 4)) * 8;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 8]);
    m0 = max(m0, input[base + 16]);
    m0 = max(m0, input[base + 24]);
    m0 = max(m0, input[base + 224]);
    m0 = max(m0, input[base + 232]);
    m0 = max(m0, input[base + 240]);
    m0 = max(m0, input[base + 248]);
    m0 = max(m0, input[base + 448]);
    m0 = max(m0, input[base + 456]);
    m0 = max(m0, input[base + 464]);
    m0 = max(m0, input[base + 472]);
    m0 = max(m0, input[base + 672]);
    m0 = max(m0, input[base + 680]);
    m0 = max(m0, input[base + 688]);
    m0 = max(m0, input[base + 696]);
    output[(oy * 7 + ox) * 8 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 9]);
    m1 = max(m1, input[base + 17]);
    m1 = max(m1, input[base + 25]);
    m1 = max(m1, input[base + 225]);
    m1 = max(m1, input[base + 233]);
    m1 = max(m1, input[base + 241]);
    m1 = max(m1, input[base + 249]);
    m1 = max(m1, input[base + 449]);
    m1 = max(m1, input[base + 457]);
    m1 = max(m1, input[base + 465]);
    m1 = max(m1, input[base + 473]);
    m1 = max(m1, input[base + 673]);
    m1 = max(m1, input[base + 681]);
    m1 = max(m1, input[base + 689]);
    m1 = max(m1, input[base + 697]);
    output[(oy * 7 + ox) * 8 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 10]);
    m2 = max(m2, input[base + 18]);
    m2 = max(m2, input[base + 26]);
    m2 = max(m2, input[base + 226]);
    m2 = max(m2, input[base + 234]);
    m2 = max(m2, input[base + 242]);
    m2 = max(m2, input[base + 250]);
    m2 = max(m2, input[base + 450]);
    m2 = max(m2, input[base + 458]);
    m2 = max(m2, input[base + 466]);
    m2 = max(m2, input[base + 474]);
    m2 = max(m2, input[base + 674]);
    m2 = max(m2, input[base + 682]);
    m2 = max(m2, input[base + 690]);
    m2 = max(m2, input[base + 698]);
    output[(oy * 7 + ox) * 8 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 11]);
    m3 = max(m3, input[base + 19]);
    m3 = max(m3, input[base + 27]);
    m3 = max(m3, input[base + 227]);
    m3 = max(m3, input[base + 235]);
    m3 = max(m3, input[base + 243]);
    m3 = max(m3, input[base + 251]);
    m3 = max(m3, input[base + 451]);
    m3 = max(m3, input[base + 459]);
    m3 = max(m3, input[base + 467]);
    m3 = max(m3, input[base + 475]);
    m3 = max(m3, input[base + 675]);
    m3 = max(m3, input[base + 683]);
    m3 = max(m3, input[base + 691]);
    m3 = max(m3, input[base + 699]);
    output[(oy * 7 + ox) * 8 + 3] = m3;

    // channel 4
    float m4 = -INFINITY;
    m4 = max(m4, input[base + 4]);
    m4 = max(m4, input[base + 12]);
    m4 = max(m4, input[base + 20]);
    m4 = max(m4, input[base + 28]);
    m4 = max(m4, input[base + 228]);
    m4 = max(m4, input[base + 236]);
    m4 = max(m4, input[base + 244]);
    m4 = max(m4, input[base + 252]);
    m4 = max(m4, input[base + 452]);
    m4 = max(m4, input[base + 460]);
    m4 = max(m4, input[base + 468]);
    m4 = max(m4, input[base + 476]);
    m4 = max(m4, input[base + 676]);
    m4 = max(m4, input[base + 684]);
    m4 = max(m4, input[base + 692]);
    m4 = max(m4, input[base + 700]);
    output[(oy * 7 + ox) * 8 + 4] = m4;

    // channel 5
    float m5 = -INFINITY;
    m5 = max(m5, input[base + 5]);
    m5 = max(m5, input[base + 13]);
    m5 = max(m5, input[base + 21]);
    m5 = max(m5, input[base + 29]);
    m5 = max(m5, input[base + 229]);
    m5 = max(m5, input[base + 237]);
    m5 = max(m5, input[base + 245]);
    m5 = max(m5, input[base + 253]);
    m5 = max(m5, input[base + 453]);
    m5 = max(m5, input[base + 461]);
    m5 = max(m5, input[base + 469]);
    m5 = max(m5, input[base + 477]);
    m5 = max(m5, input[base + 677]);
    m5 = max(m5, input[base + 685]);
    m5 = max(m5, input[base + 693]);
    m5 = max(m5, input[base + 701]);
    output[(oy * 7 + ox) * 8 + 5] = m5;

    // channel 6
    float m6 = -INFINITY;
    m6 = max(m6, input[base + 6]);
    m6 = max(m6, input[base + 14]);
    m6 = max(m6, input[base + 22]);
    m6 = max(m6, input[base + 30]);
    m6 = max(m6, input[base + 230]);
    m6 = max(m6, input[base + 238]);
    m6 = max(m6, input[base + 246]);
    m6 = max(m6, input[base + 254]);
    m6 = max(m6, input[base + 454]);
    m6 = max(m6, input[base + 462]);
    m6 = max(m6, input[base + 470]);
    m6 = max(m6, input[base + 478]);
    m6 = max(m6, input[base + 678]);
    m6 = max(m6, input[base + 686]);
    m6 = max(m6, input[base + 694]);
    m6 = max(m6, input[base + 702]);
    output[(oy * 7 + ox) * 8 + 6] = m6;

    // channel 7
    float m7 = -INFINITY;
    m7 = max(m7, input[base + 7]);
    m7 = max(m7, input[base + 15]);
    m7 = max(m7, input[base + 23]);
    m7 = max(m7, input[base + 31]);
    m7 = max(m7, input[base + 231]);
    m7 = max(m7, input[base + 239]);
    m7 = max(m7, input[base + 247]);
    m7 = max(m7, input[base + 255]);
    m7 = max(m7, input[base + 455]);
    m7 = max(m7, input[base + 463]);
    m7 = max(m7, input[base + 471]);
    m7 = max(m7, input[base + 479]);
    m7 = max(m7, input[base + 679]);
    m7 = max(m7, input[base + 687]);
    m7 = max(m7, input[base + 695]);
    m7 = max(m7, input[base + 703]);
    output[(oy * 7 + ox) * 8 + 7] = m7;

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=1 filterSize=3
// params: input, filterWeights, filterBias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    const float filterBias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 14 + (x - 1) * 1;
        sum += input[base_0_0] * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 14 + x * 1;
        sum += input[base_0_1] * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 13)
    {
        const int base_0_2 = (y - 1) * 14 + (x + 1) * 1;
        sum += input[base_0_2] * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 14 + (x - 1) * 1;
        sum += input[base_1_0] * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 14 + x * 1;
    sum += input[base_1_1] * filterWeights[4];

    // tap (1, 2)
    if (x < 13)
    {
        const int base_1_2 = y * 14 + (x + 1) * 1;
        sum += input[base_1_2] * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 13 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 14 + (x - 1) * 1;
        sum += input[base_2_0] * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 13)
    {
        const int base_2_1 = (y + 1) * 14 + x * 1;
        sum += input[base_2_1] * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 13 && x < 13)
    {
        const int base_2_2 = (y + 1) * 14 + (x + 1) * 1;
        sum += input[base_2_2] * filterWeights[8];
    }

    sum += filterBias;

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 14 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=1 poolSize=2 -> 7x7
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 14]);
    m0 = max(m0, input[base + 15]);
    output[(oy * 7 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dDense_i49_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=49 outputFloats=10
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i49_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 49; i++)
        sum += input[i] * weights[o * 49 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}
