enum ActivationFunction {
    ReLU,
    Sigmoid,
    Tanh,
    None,
};

__kernel void cnn2dFilter(
    __global float* input,
    const int channels,
    const int width,
    const int height,

    __global float* filterWeights,
    const float filterBias,
    const int filterSize,

    __global float* output,
    const int activation
) {
    const int x = get_global_id(0);
    const int y = get_global_id(1);

    const int pad = filterSize / 2;
    float sum = 0.0f;

    for (int j = 0; j < filterSize; j++) {
        int iy = y + j - pad;
        if (iy < 0 || iy >= height) continue;
        for (int i = 0; i < filterSize; i++) {
            int ix = x + i - pad;
            if (ix < 0 || ix >= width) continue;
            for (int k = 0; k < channels; k++) {
                sum += input[iy * width * channels + ix * channels + k]
                     * filterWeights[j * filterSize * channels + i * channels + k];
            }
        }
    }

    sum += filterBias;

    switch (activation) {
        case ReLU:    output[y * width + x] = max(sum, 0.0f); break;
        case Sigmoid: output[y * width + x] = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    output[y * width + x] = tanh(sum); break;
        case None:    output[y * width + x] = sum; break;
    }
}





// ---------------------------------------------------------------------------
// cnn2dFilter_w64_h64_c3_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=64 height=64 channels=3 filterSize=3 filters=1
// dims: in 64x64x3 -> out 64x64x1 (output channels = 1) | weights [1][3][3][3] | bias [1]
// plan: 1 filter(s) in registers, scalar channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w64_h64_c3_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 64 || y >= 64) return;

    float a0 = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 192 + (x - 1) * 3;
        const float v0 = input[base_0_0];
        a0 += v0 * filterWeights[0];
        const float v1 = input[base_0_0 + 1];
        a0 += v1 * filterWeights[1];
        const float v2 = input[base_0_0 + 2];
        a0 += v2 * filterWeights[2];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 192 + x * 3;
        const float v0 = input[base_0_1];
        a0 += v0 * filterWeights[3];
        const float v1 = input[base_0_1 + 1];
        a0 += v1 * filterWeights[4];
        const float v2 = input[base_0_1 + 2];
        a0 += v2 * filterWeights[5];
    }

    // tap (0, 2)
    if (y >= 1 && x < 63)
    {
        const int base_0_2 = (y - 1) * 192 + (x + 1) * 3;
        const float v0 = input[base_0_2];
        a0 += v0 * filterWeights[6];
        const float v1 = input[base_0_2 + 1];
        a0 += v1 * filterWeights[7];
        const float v2 = input[base_0_2 + 2];
        a0 += v2 * filterWeights[8];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 192 + (x - 1) * 3;
        const float v0 = input[base_1_0];
        a0 += v0 * filterWeights[9];
        const float v1 = input[base_1_0 + 1];
        a0 += v1 * filterWeights[10];
        const float v2 = input[base_1_0 + 2];
        a0 += v2 * filterWeights[11];
    }

    // tap (1, 1)
    const int base_1_1 = y * 192 + x * 3;
    const float v0 = input[base_1_1];
    a0 += v0 * filterWeights[12];
    const float v1 = input[base_1_1 + 1];
    a0 += v1 * filterWeights[13];
    const float v2 = input[base_1_1 + 2];
    a0 += v2 * filterWeights[14];

    // tap (1, 2)
    if (x < 63)
    {
        const int base_1_2 = y * 192 + (x + 1) * 3;
        const float v0 = input[base_1_2];
        a0 += v0 * filterWeights[15];
        const float v1 = input[base_1_2 + 1];
        a0 += v1 * filterWeights[16];
        const float v2 = input[base_1_2 + 2];
        a0 += v2 * filterWeights[17];
    }

    // tap (2, 0)
    if (y < 63 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 192 + (x - 1) * 3;
        const float v0 = input[base_2_0];
        a0 += v0 * filterWeights[18];
        const float v1 = input[base_2_0 + 1];
        a0 += v1 * filterWeights[19];
        const float v2 = input[base_2_0 + 2];
        a0 += v2 * filterWeights[20];
    }

    // tap (2, 1)
    if (y < 63)
    {
        const int base_2_1 = (y + 1) * 192 + x * 3;
        const float v0 = input[base_2_1];
        a0 += v0 * filterWeights[21];
        const float v1 = input[base_2_1 + 1];
        a0 += v1 * filterWeights[22];
        const float v2 = input[base_2_1 + 2];
        a0 += v2 * filterWeights[23];
    }

    // tap (2, 2)
    if (y < 63 && x < 63)
    {
        const int base_2_2 = (y + 1) * 192 + (x + 1) * 3;
        const float v0 = input[base_2_2];
        a0 += v0 * filterWeights[24];
        const float v1 = input[base_2_2 + 1];
        a0 += v1 * filterWeights[25];
        const float v2 = input[base_2_2 + 2];
        a0 += v2 * filterWeights[26];
    }

    {
        float sum = a0 + bias[0];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 64 + x) * 1 + 0;
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=1
// dims: in 28x28x1 -> out 28x28x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// plan: 1 filter(s) in registers, scalar channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float a0 = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_0_0];
        a0 += v0 * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 28 + x * 1;
        const float v0 = input[base_0_1];
        a0 += v0 * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_0_2];
        a0 += v0 * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 28 + (x - 1) * 1;
        const float v0 = input[base_1_0];
        a0 += v0 * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 28 + x * 1;
    const float v0 = input[base_1_1];
    a0 += v0 * filterWeights[4];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 28 + (x + 1) * 1;
        const float v0 = input[base_1_2];
        a0 += v0 * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_2_0];
        a0 += v0 * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 28 + x * 1;
        const float v0 = input[base_2_1];
        a0 += v0 * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_2_2];
        a0 += v0 * filterWeights[8];
    }

    {
        float sum = a0 + bias[0];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 1 + 0;
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c4_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=4 filterSize=3 filters=1
// dims: in 28x28x4 -> out 28x28x1 (output channels = 1) | weights [1][3][3][4] | bias [1]
// plan: 1 filter(s) in registers, float4 channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c4_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float4 a0 = (float4)(0.0f);

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 112 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 0);
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 112 + x * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_1);
        a0 += v0 * *(__global const float4*)(filterWeights + 4);
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 112 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 8);
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 112 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_1_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 12);
    }

    // tap (1, 1)
    const int base_1_1 = y * 112 + x * 4;
    const float4 v0 = *(__global const float4*)(input + base_1_1);
    a0 += v0 * *(__global const float4*)(filterWeights + 16);

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 112 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_1_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 20);
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 112 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 24);
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 112 + x * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_1);
        a0 += v0 * *(__global const float4*)(filterWeights + 28);
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 112 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 32);
    }

    {
        float sum = (a0.x + a0.y) + (a0.z + a0.w) + bias[0];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 1 + 0;
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c8_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=8 filterSize=3 filters=1
// dims: in 28x28x8 -> out 28x28x1 (output channels = 1) | weights [1][3][3][8] | bias [1]
// plan: 1 filter(s) in registers, float4 channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c8_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float4 a0 = (float4)(0.0f);

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 224 + (x - 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_0_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 0);
        const float4 v1 = *(__global const float4*)(input + base_0_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 4);
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 224 + x * 8;
        const float4 v0 = *(__global const float4*)(input + base_0_1);
        a0 += v0 * *(__global const float4*)(filterWeights + 8);
        const float4 v1 = *(__global const float4*)(input + base_0_1 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 12);
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 224 + (x + 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_0_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 16);
        const float4 v1 = *(__global const float4*)(input + base_0_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 20);
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 224 + (x - 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_1_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 24);
        const float4 v1 = *(__global const float4*)(input + base_1_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 28);
    }

    // tap (1, 1)
    const int base_1_1 = y * 224 + x * 8;
    const float4 v0 = *(__global const float4*)(input + base_1_1);
    a0 += v0 * *(__global const float4*)(filterWeights + 32);
    const float4 v1 = *(__global const float4*)(input + base_1_1 + 4);
    a0 += v1 * *(__global const float4*)(filterWeights + 36);

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 224 + (x + 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_1_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 40);
        const float4 v1 = *(__global const float4*)(input + base_1_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 44);
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 224 + (x - 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_2_0);
        a0 += v0 * *(__global const float4*)(filterWeights + 48);
        const float4 v1 = *(__global const float4*)(input + base_2_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 52);
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 224 + x * 8;
        const float4 v0 = *(__global const float4*)(input + base_2_1);
        a0 += v0 * *(__global const float4*)(filterWeights + 56);
        const float4 v1 = *(__global const float4*)(input + base_2_1 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 60);
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 224 + (x + 1) * 8;
        const float4 v0 = *(__global const float4*)(input + base_2_2);
        a0 += v0 * *(__global const float4*)(filterWeights + 64);
        const float4 v1 = *(__global const float4*)(input + base_2_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + 68);
    }

    {
        float sum = (a0.x + a0.y) + (a0.z + a0.w) + bias[0];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 1 + 0;
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=1 filterSize=3 filters=1
// dims: in 14x14x1 -> out 14x14x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// plan: 1 filter(s) in registers, scalar channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14) return;

    float a0 = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 14 + (x - 1) * 1;
        const float v0 = input[base_0_0];
        a0 += v0 * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 14 + x * 1;
        const float v0 = input[base_0_1];
        a0 += v0 * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 13)
    {
        const int base_0_2 = (y - 1) * 14 + (x + 1) * 1;
        const float v0 = input[base_0_2];
        a0 += v0 * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 14 + (x - 1) * 1;
        const float v0 = input[base_1_0];
        a0 += v0 * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 14 + x * 1;
    const float v0 = input[base_1_1];
    a0 += v0 * filterWeights[4];

    // tap (1, 2)
    if (x < 13)
    {
        const int base_1_2 = y * 14 + (x + 1) * 1;
        const float v0 = input[base_1_2];
        a0 += v0 * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 13 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 14 + (x - 1) * 1;
        const float v0 = input[base_2_0];
        a0 += v0 * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 13)
    {
        const int base_2_1 = (y + 1) * 14 + x * 1;
        const float v0 = input[base_2_1];
        a0 += v0 * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 13 && x < 13)
    {
        const int base_2_2 = (y + 1) * 14 + (x + 1) * 1;
        const float v0 = input[base_2_2];
        a0 += v0 * filterWeights[8];
    }

    {
        float sum = a0 + bias[0];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 1 + 0;
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3_n4 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=4
// dims: in 28x28x1 -> out 28x28x4 (output channels = 4) | weights [4][3][3][1] | bias [4]
// plan: 1 filter(s) in registers, 4 filter groups over global_id(0), scalar channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3_n4(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int g0 = get_global_id(0);
    const int x = g0 % 28;
    const int n0 = (g0 / 28) * 1;
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28 || n0 >= 4) return;

    float a0 = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_0_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 28 + x * 1;
        const float v0 = input[base_0_1];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_0_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 28 + (x - 1) * 1;
        const float v0 = input[base_1_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 28 + x * 1;
    const float v0 = input[base_1_1];
    a0 += v0 * filterWeights[(n0 + 0) * 9 + 4];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 28 + (x + 1) * 1;
        const float v0 = input[base_1_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 5];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_2_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 6];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 28 + x * 1;
        const float v0 = input[base_2_1];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 7];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_2_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 8];
    }

    {
        float sum = a0 + bias[(n0 + 0)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 4 + (n0 + 0);
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c4_f3_n4 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=4 filterSize=3 filters=4
// dims: in 14x14x4 -> out 14x14x4 (output channels = 4) | weights [4][3][3][4] | bias [4]
// plan: 1 filter(s) in registers, 4 filter groups over global_id(0), float4 channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c4_f3_n4(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int g0 = get_global_id(0);
    const int x = g0 % 14;
    const int n0 = (g0 / 14) * 1;
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14 || n0 >= 4) return;

    float4 a0 = (float4)(0.0f);

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 56 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 0);
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 56 + x * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_1);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 4);
    }

    // tap (0, 2)
    if (y >= 1 && x < 13)
    {
        const int base_0_2 = (y - 1) * 56 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_0_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 8);
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 56 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_1_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 12);
    }

    // tap (1, 1)
    const int base_1_1 = y * 56 + x * 4;
    const float4 v0 = *(__global const float4*)(input + base_1_1);
    a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 16);

    // tap (1, 2)
    if (x < 13)
    {
        const int base_1_2 = y * 56 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_1_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 20);
    }

    // tap (2, 0)
    if (y < 13 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 56 + (x - 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 24);
    }

    // tap (2, 1)
    if (y < 13)
    {
        const int base_2_1 = (y + 1) * 56 + x * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_1);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 28);
    }

    // tap (2, 2)
    if (y < 13 && x < 13)
    {
        const int base_2_2 = (y + 1) * 56 + (x + 1) * 4;
        const float4 v0 = *(__global const float4*)(input + base_2_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 36 + 32);
    }

    {
        float sum = (a0.x + a0.y) + (a0.z + a0.w) + bias[(n0 + 0)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 4 + (n0 + 0);
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=1 poolSize=2 -> 14x14
// dims: in 28x28x1 -> out 14x14x1 (max pool 2x2, per channel)
// plan: scalar channels
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 28]);
    m0 = max(m0, input[base + 29]);
    output[(oy * 14 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c8_p4 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=8 poolSize=4 -> 7x7
// dims: in 28x28x8 -> out 7x7x8 (max pool 4x4, per channel)
// plan: float4 channel quads, 2 channel groups over global_id(0)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c8_p4(
    __global const float* input,
    __global float* output)
{
    const int g0 = get_global_id(0);
    const int ox = g0 / 2;
    const int cq = g0 % 2;
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 4) * 28 + (ox * 4)) * 8 + cq * 4;

    // one float4 covers 4 adjacent channels: max is exact, so the
    // vectorised reduction is bit-identical to the scalar one
    float4 m = (float4)(-INFINITY);
    m = max(m, *(__global const float4*)(input + base));
    m = max(m, *(__global const float4*)(input + base + 8));
    m = max(m, *(__global const float4*)(input + base + 16));
    m = max(m, *(__global const float4*)(input + base + 24));
    m = max(m, *(__global const float4*)(input + base + 224));
    m = max(m, *(__global const float4*)(input + base + 232));
    m = max(m, *(__global const float4*)(input + base + 240));
    m = max(m, *(__global const float4*)(input + base + 248));
    m = max(m, *(__global const float4*)(input + base + 448));
    m = max(m, *(__global const float4*)(input + base + 456));
    m = max(m, *(__global const float4*)(input + base + 464));
    m = max(m, *(__global const float4*)(input + base + 472));
    m = max(m, *(__global const float4*)(input + base + 672));
    m = max(m, *(__global const float4*)(input + base + 680));
    m = max(m, *(__global const float4*)(input + base + 688));
    m = max(m, *(__global const float4*)(input + base + 696));

    *(__global float4*)(output + (oy * 7 + ox) * 8 + cq * 4) = m;
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=1 poolSize=2 -> 7x7
// dims: in 14x14x1 -> out 7x7x1 (max pool 2x2, per channel)
// plan: scalar channels
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 14]);
    m0 = max(m0, input[base + 15]);
    output[(oy * 7 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=4 poolSize=2 -> 14x14
// dims: in 28x28x4 -> out 14x14x4 (max pool 2x2, per channel)
// plan: float4 channel quads, 1 channel groups over global_id(0)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c4_p2(
    __global const float* input,
    __global float* output)
{
    const int g0 = get_global_id(0);
    const int ox = g0 / 1;
    const int cq = g0 % 1;
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 4 + cq * 4;

    // one float4 covers 4 adjacent channels: max is exact, so the
    // vectorised reduction is bit-identical to the scalar one
    float4 m = (float4)(-INFINITY);
    m = max(m, *(__global const float4*)(input + base));
    m = max(m, *(__global const float4*)(input + base + 4));
    m = max(m, *(__global const float4*)(input + base + 112));
    m = max(m, *(__global const float4*)(input + base + 116));

    *(__global float4*)(output + (oy * 14 + ox) * 4 + cq * 4) = m;
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=4 poolSize=2 -> 7x7
// dims: in 14x14x4 -> out 7x7x4 (max pool 2x2, per channel)
// plan: float4 channel quads, 1 channel groups over global_id(0)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c4_p2(
    __global const float* input,
    __global float* output)
{
    const int g0 = get_global_id(0);
    const int ox = g0 / 1;
    const int cq = g0 % 1;
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 4 + cq * 4;

    // one float4 covers 4 adjacent channels: max is exact, so the
    // vectorised reduction is bit-identical to the scalar one
    float4 m = (float4)(-INFINITY);
    m = max(m, *(__global const float4*)(input + base));
    m = max(m, *(__global const float4*)(input + base + 4));
    m = max(m, *(__global const float4*)(input + base + 56));
    m = max(m, *(__global const float4*)(input + base + 60));

    *(__global float4*)(output + (oy * 7 + ox) * 4 + cq * 4) = m;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i196_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=196 outputFloats=10
// dims: in 196 -> out 10 | weights [10][196] | bias [10]
// plan: float4 input/weight loads, 4 accumulator lanes
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i196_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    const int base = o * 196;
    float4 a = (float4)(0.0f);
    for (int i = 0; i < 49; i++)
        a += *(__global const float4*)(input + 4 * i) * *(__global const float4*)(weights + base + 4 * i);

    float sum = (a.x + a.y) + (a.z + a.w);
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i49_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=49 outputFloats=10
// dims: in 49 -> out 10 | weights [10][49] | bias [10]
// plan: scalar loads
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i49_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 49; i++)
        sum += input[i] * weights[o * 49 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dSoftmax_n10 -- generated by generateKernel.py (do not edit by hand)
// count=10 (softmax over the whole vector)
// dims: in 10 -> out 10 (probability distribution, sums to 1)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dSoftmax_n10(
    __global const float* input,
    __global float* output)
{
    if (get_global_id(0) != 0) return;

    float m = -INFINITY;
    for (int i = 0; i < 10; i++)
        m = max(m, input[i]);

    float s = 0.0f;
    for (int i = 0; i < 10; i++)
        s += exp(input[i] - m);

    for (int i = 0; i < 10; i++)
        output[i] = exp(input[i] - m) / s;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3_n16 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=16
// dims: in 28x28x1 -> out 28x28x16 (output channels = 16) | weights [16][3][3][1] | bias [16]
// plan: 4 filter(s) in registers, 4 filter groups over global_id(0), scalar channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3_n16(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int g0 = get_global_id(0);
    const int x = g0 % 28;
    const int n0 = (g0 / 28) * 4;
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28 || n0 >= 16) return;

    float a0 = 0.0f;
    float a1 = 0.0f;
    float a2 = 0.0f;
    float a3 = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_0_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 0];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 0];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 0];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 28 + x * 1;
        const float v0 = input[base_0_1];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 1];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 1];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 1];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_0_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 2];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 2];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 2];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 28 + (x - 1) * 1;
        const float v0 = input[base_1_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 3];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 3];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 3];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 28 + x * 1;
    const float v0 = input[base_1_1];
    a0 += v0 * filterWeights[(n0 + 0) * 9 + 4];
    a1 += v0 * filterWeights[(n0 + 1) * 9 + 4];
    a2 += v0 * filterWeights[(n0 + 2) * 9 + 4];
    a3 += v0 * filterWeights[(n0 + 3) * 9 + 4];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 28 + (x + 1) * 1;
        const float v0 = input[base_1_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 5];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 5];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 5];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 5];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
        const float v0 = input[base_2_0];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 6];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 6];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 6];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 6];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 28 + x * 1;
        const float v0 = input[base_2_1];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 7];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 7];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 7];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 7];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
        const float v0 = input[base_2_2];
        a0 += v0 * filterWeights[(n0 + 0) * 9 + 8];
        a1 += v0 * filterWeights[(n0 + 1) * 9 + 8];
        a2 += v0 * filterWeights[(n0 + 2) * 9 + 8];
        a3 += v0 * filterWeights[(n0 + 3) * 9 + 8];
    }

    {
        float sum = a0 + bias[(n0 + 0)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 16 + (n0 + 0);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = a1 + bias[(n0 + 1)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 16 + (n0 + 1);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = a2 + bias[(n0 + 2)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 16 + (n0 + 2);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = a3 + bias[(n0 + 3)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 16 + (n0 + 3);
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c16_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=16 poolSize=2 -> 14x14
// dims: in 28x28x16 -> out 14x14x16 (max pool 2x2, per channel)
// plan: float4 channel quads, 4 channel groups over global_id(0)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c16_p2(
    __global const float* input,
    __global float* output)
{
    const int g0 = get_global_id(0);
    const int ox = g0 / 4;
    const int cq = g0 % 4;
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 16 + cq * 4;

    // one float4 covers 4 adjacent channels: max is exact, so the
    // vectorised reduction is bit-identical to the scalar one
    float4 m = (float4)(-INFINITY);
    m = max(m, *(__global const float4*)(input + base));
    m = max(m, *(__global const float4*)(input + base + 16));
    m = max(m, *(__global const float4*)(input + base + 448));
    m = max(m, *(__global const float4*)(input + base + 464));

    *(__global float4*)(output + (oy * 14 + ox) * 16 + cq * 4) = m;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c16_f3_n32 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=16 filterSize=3 filters=32
// dims: in 14x14x16 -> out 14x14x32 (output channels = 32) | weights [32][3][3][16] | bias [32]
// plan: 4 filter(s) in registers, 8 filter groups over global_id(0), float4 channel loads
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c16_f3_n32(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int g0 = get_global_id(0);
    const int x = g0 % 14;
    const int n0 = (g0 / 14) * 4;
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14 || n0 >= 32) return;

    float4 a0 = (float4)(0.0f);
    float4 a1 = (float4)(0.0f);
    float4 a2 = (float4)(0.0f);
    float4 a3 = (float4)(0.0f);

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 224 + (x - 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_0_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 0);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 0);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 0);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 0);
        const float4 v1 = *(__global const float4*)(input + base_0_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 4);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 4);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 4);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 4);
        const float4 v2 = *(__global const float4*)(input + base_0_0 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 8);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 8);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 8);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 8);
        const float4 v3 = *(__global const float4*)(input + base_0_0 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 12);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 12);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 12);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 12);
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 224 + x * 16;
        const float4 v0 = *(__global const float4*)(input + base_0_1);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 16);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 16);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 16);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 16);
        const float4 v1 = *(__global const float4*)(input + base_0_1 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 20);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 20);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 20);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 20);
        const float4 v2 = *(__global const float4*)(input + base_0_1 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 24);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 24);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 24);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 24);
        const float4 v3 = *(__global const float4*)(input + base_0_1 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 28);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 28);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 28);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 28);
    }

    // tap (0, 2)
    if (y >= 1 && x < 13)
    {
        const int base_0_2 = (y - 1) * 224 + (x + 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_0_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 32);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 32);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 32);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 32);
        const float4 v1 = *(__global const float4*)(input + base_0_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 36);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 36);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 36);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 36);
        const float4 v2 = *(__global const float4*)(input + base_0_2 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 40);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 40);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 40);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 40);
        const float4 v3 = *(__global const float4*)(input + base_0_2 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 44);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 44);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 44);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 44);
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 224 + (x - 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_1_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 48);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 48);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 48);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 48);
        const float4 v1 = *(__global const float4*)(input + base_1_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 52);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 52);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 52);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 52);
        const float4 v2 = *(__global const float4*)(input + base_1_0 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 56);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 56);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 56);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 56);
        const float4 v3 = *(__global const float4*)(input + base_1_0 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 60);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 60);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 60);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 60);
    }

    // tap (1, 1)
    const int base_1_1 = y * 224 + x * 16;
    const float4 v0 = *(__global const float4*)(input + base_1_1);
    a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 64);
    a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 64);
    a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 64);
    a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 64);
    const float4 v1 = *(__global const float4*)(input + base_1_1 + 4);
    a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 68);
    a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 68);
    a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 68);
    a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 68);
    const float4 v2 = *(__global const float4*)(input + base_1_1 + 8);
    a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 72);
    a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 72);
    a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 72);
    a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 72);
    const float4 v3 = *(__global const float4*)(input + base_1_1 + 12);
    a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 76);
    a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 76);
    a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 76);
    a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 76);

    // tap (1, 2)
    if (x < 13)
    {
        const int base_1_2 = y * 224 + (x + 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_1_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 80);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 80);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 80);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 80);
        const float4 v1 = *(__global const float4*)(input + base_1_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 84);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 84);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 84);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 84);
        const float4 v2 = *(__global const float4*)(input + base_1_2 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 88);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 88);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 88);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 88);
        const float4 v3 = *(__global const float4*)(input + base_1_2 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 92);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 92);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 92);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 92);
    }

    // tap (2, 0)
    if (y < 13 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 224 + (x - 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_2_0);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 96);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 96);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 96);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 96);
        const float4 v1 = *(__global const float4*)(input + base_2_0 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 100);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 100);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 100);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 100);
        const float4 v2 = *(__global const float4*)(input + base_2_0 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 104);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 104);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 104);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 104);
        const float4 v3 = *(__global const float4*)(input + base_2_0 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 108);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 108);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 108);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 108);
    }

    // tap (2, 1)
    if (y < 13)
    {
        const int base_2_1 = (y + 1) * 224 + x * 16;
        const float4 v0 = *(__global const float4*)(input + base_2_1);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 112);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 112);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 112);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 112);
        const float4 v1 = *(__global const float4*)(input + base_2_1 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 116);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 116);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 116);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 116);
        const float4 v2 = *(__global const float4*)(input + base_2_1 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 120);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 120);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 120);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 120);
        const float4 v3 = *(__global const float4*)(input + base_2_1 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 124);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 124);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 124);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 124);
    }

    // tap (2, 2)
    if (y < 13 && x < 13)
    {
        const int base_2_2 = (y + 1) * 224 + (x + 1) * 16;
        const float4 v0 = *(__global const float4*)(input + base_2_2);
        a0 += v0 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 128);
        a1 += v0 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 128);
        a2 += v0 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 128);
        a3 += v0 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 128);
        const float4 v1 = *(__global const float4*)(input + base_2_2 + 4);
        a0 += v1 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 132);
        a1 += v1 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 132);
        a2 += v1 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 132);
        a3 += v1 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 132);
        const float4 v2 = *(__global const float4*)(input + base_2_2 + 8);
        a0 += v2 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 136);
        a1 += v2 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 136);
        a2 += v2 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 136);
        a3 += v2 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 136);
        const float4 v3 = *(__global const float4*)(input + base_2_2 + 12);
        a0 += v3 * *(__global const float4*)(filterWeights + (n0 + 0) * 144 + 140);
        a1 += v3 * *(__global const float4*)(filterWeights + (n0 + 1) * 144 + 140);
        a2 += v3 * *(__global const float4*)(filterWeights + (n0 + 2) * 144 + 140);
        a3 += v3 * *(__global const float4*)(filterWeights + (n0 + 3) * 144 + 140);
    }

    {
        float sum = (a0.x + a0.y) + (a0.z + a0.w) + bias[(n0 + 0)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 32 + (n0 + 0);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = (a1.x + a1.y) + (a1.z + a1.w) + bias[(n0 + 1)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 32 + (n0 + 1);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = (a2.x + a2.y) + (a2.z + a2.w) + bias[(n0 + 2)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 32 + (n0 + 2);
        output[idx] = accumulate ? output[idx] + value : value;
    }

    {
        float sum = (a3.x + a3.y) + (a3.z + a3.w) + bias[(n0 + 3)];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 32 + (n0 + 3);
        output[idx] = accumulate ? output[idx] + value : value;
    }

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c32_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=32 poolSize=2 -> 7x7
// dims: in 14x14x32 -> out 7x7x32 (max pool 2x2, per channel)
// plan: float4 channel quads, 8 channel groups over global_id(0)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c32_p2(
    __global const float* input,
    __global float* output)
{
    const int g0 = get_global_id(0);
    const int ox = g0 / 8;
    const int cq = g0 % 8;
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 32 + cq * 4;

    // one float4 covers 4 adjacent channels: max is exact, so the
    // vectorised reduction is bit-identical to the scalar one
    float4 m = (float4)(-INFINITY);
    m = max(m, *(__global const float4*)(input + base));
    m = max(m, *(__global const float4*)(input + base + 32));
    m = max(m, *(__global const float4*)(input + base + 448));
    m = max(m, *(__global const float4*)(input + base + 480));

    *(__global float4*)(output + (oy * 7 + ox) * 32 + cq * 4) = m;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i1568_o128 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=1568 outputFloats=128
// dims: in 1568 -> out 128 | weights [128][1568] | bias [128]
// plan: float4 loads, 64 work items per output, __local tree reduce
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i1568_o128(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0) / 64;
    const int lid = get_global_id(0) % 64;
    if (o >= 128) return;

    const int base = o * 1568;
    float4 a = (float4)(0.0f);
    for (int i = lid; i < 392; i += 64)
        a += *(__global const float4*)(input + 4 * i) * *(__global const float4*)(weights + base + 4 * i);

    __local float part[64];
    part[lid] = (a.x + a.y) + (a.z + a.w);
    barrier(CLK_LOCAL_MEM_FENCE);
    for (int step = 32; step > 0; step >>= 1)
    {
        if (lid < step) part[lid] += part[lid + step];
        barrier(CLK_LOCAL_MEM_FENCE);
    }

    if (lid != 0) return;

    float sum = part[0];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i128_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=128 outputFloats=10
// dims: in 128 -> out 10 | weights [10][128] | bias [10]
// plan: float4 input/weight loads, 4 accumulator lanes
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i128_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    const int base = o * 128;
    float4 a = (float4)(0.0f);
    for (int i = 0; i < 32; i++)
        a += *(__global const float4*)(input + 4 * i) * *(__global const float4*)(weights + base + 4 * i);

    float sum = (a.x + a.y) + (a.z + a.w);
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dPixelShuffle_w14_h14_c1_r2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=1 upscale=2 -> 28x28
// dims: in 14x14x4 -> out 28x28x1 | pixel shuffle x2, channels-last
// out[y*2 + i][x*2 + j][c] = in[y][x][c*4 + i*2 + j]
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dPixelShuffle_w14_h14_c1_r2(
    __global const float* input,
    __global float* output)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    const int sub = (y % 2) * 2 + (x % 2);
    const int src = ((y / 2) * 14 + (x / 2)) * 4 + sub;
    const int dst = (y * 28 + x) * 1;
    for (int c = 0; c < 1; c++)
        output[dst + c] = input[src + c * 4];
}
