enum ActivationFunction {
    ReLU,
    Sigmoid,
    Tanh,
    None,
};

__kernel void cnn2dFilter(
    __global float* input,
    const int channels,
    const int width,
    const int height,

    __global float* filterWeights,
    const float filterBias,
    const int filterSize,

    __global float* output,
    const int activation
) {
    const int x = get_global_id(0);
    const int y = get_global_id(1);

    const int pad = filterSize / 2;
    float sum = 0.0f;

    for (int j = 0; j < filterSize; j++) {
        int iy = y + j - pad;
        if (iy < 0 || iy >= height) continue;
        for (int i = 0; i < filterSize; i++) {
            int ix = x + i - pad;
            if (ix < 0 || ix >= width) continue;
            for (int k = 0; k < channels; k++) {
                sum += input[iy * width * channels + ix * channels + k]
                     * filterWeights[j * filterSize * channels + i * channels + k];
            }
        }
    }

    sum += filterBias;

    switch (activation) {
        case ReLU:    output[y * width + x] = max(sum, 0.0f); break;
        case Sigmoid: output[y * width + x] = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    output[y * width + x] = tanh(sum); break;
        case None:    output[y * width + x] = sum; break;
    }
}




// ---------------------------------------------------------------------------
// cnn2dFilter_w64_h64_c3_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=64 height=64 channels=3 filterSize=3 filters=1
// dims: in 64x64x3 -> out 64x64x1 (output channels = 1) | weights [1][3][3][3] | bias [1]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w64_h64_c3_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 64 || y >= 64) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 192 + (x - 1) * 3;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 192 + x * 3;
        sum += input[base_0_1] * filterWeights[3];
        sum += input[base_0_1 + 1] * filterWeights[4];
        sum += input[base_0_1 + 2] * filterWeights[5];
    }

    // tap (0, 2)
    if (y >= 1 && x < 63)
    {
        const int base_0_2 = (y - 1) * 192 + (x + 1) * 3;
        sum += input[base_0_2] * filterWeights[6];
        sum += input[base_0_2 + 1] * filterWeights[7];
        sum += input[base_0_2 + 2] * filterWeights[8];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 192 + (x - 1) * 3;
        sum += input[base_1_0] * filterWeights[9];
        sum += input[base_1_0 + 1] * filterWeights[10];
        sum += input[base_1_0 + 2] * filterWeights[11];
    }

    // tap (1, 1)
    const int base_1_1 = y * 192 + x * 3;
    sum += input[base_1_1] * filterWeights[12];
    sum += input[base_1_1 + 1] * filterWeights[13];
    sum += input[base_1_1 + 2] * filterWeights[14];

    // tap (1, 2)
    if (x < 63)
    {
        const int base_1_2 = y * 192 + (x + 1) * 3;
        sum += input[base_1_2] * filterWeights[15];
        sum += input[base_1_2 + 1] * filterWeights[16];
        sum += input[base_1_2 + 2] * filterWeights[17];
    }

    // tap (2, 0)
    if (y < 63 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 192 + (x - 1) * 3;
        sum += input[base_2_0] * filterWeights[18];
        sum += input[base_2_0 + 1] * filterWeights[19];
        sum += input[base_2_0 + 2] * filterWeights[20];
    }

    // tap (2, 1)
    if (y < 63)
    {
        const int base_2_1 = (y + 1) * 192 + x * 3;
        sum += input[base_2_1] * filterWeights[21];
        sum += input[base_2_1 + 1] * filterWeights[22];
        sum += input[base_2_1 + 2] * filterWeights[23];
    }

    // tap (2, 2)
    if (y < 63 && x < 63)
    {
        const int base_2_2 = (y + 1) * 192 + (x + 1) * 3;
        sum += input[base_2_2] * filterWeights[24];
        sum += input[base_2_2 + 1] * filterWeights[25];
        sum += input[base_2_2 + 2] * filterWeights[26];
    }

    sum += bias[0];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 64 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=1
// dims: in 28x28x1 -> out 28x28x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
        sum += input[base_0_0] * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 28 + x * 1;
        sum += input[base_0_1] * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
        sum += input[base_0_2] * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 28 + (x - 1) * 1;
        sum += input[base_1_0] * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 28 + x * 1;
    sum += input[base_1_1] * filterWeights[4];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 28 + (x + 1) * 1;
        sum += input[base_1_2] * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
        sum += input[base_2_0] * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 28 + x * 1;
        sum += input[base_2_1] * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
        sum += input[base_2_2] * filterWeights[8];
    }

    sum += bias[0];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c4_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=4 filterSize=3 filters=1
// dims: in 28x28x4 -> out 28x28x1 (output channels = 1) | weights [1][3][3][4] | bias [1]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c4_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 112 + (x - 1) * 4;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
        sum += input[base_0_0 + 3] * filterWeights[3];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 112 + x * 4;
        sum += input[base_0_1] * filterWeights[4];
        sum += input[base_0_1 + 1] * filterWeights[5];
        sum += input[base_0_1 + 2] * filterWeights[6];
        sum += input[base_0_1 + 3] * filterWeights[7];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 112 + (x + 1) * 4;
        sum += input[base_0_2] * filterWeights[8];
        sum += input[base_0_2 + 1] * filterWeights[9];
        sum += input[base_0_2 + 2] * filterWeights[10];
        sum += input[base_0_2 + 3] * filterWeights[11];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 112 + (x - 1) * 4;
        sum += input[base_1_0] * filterWeights[12];
        sum += input[base_1_0 + 1] * filterWeights[13];
        sum += input[base_1_0 + 2] * filterWeights[14];
        sum += input[base_1_0 + 3] * filterWeights[15];
    }

    // tap (1, 1)
    const int base_1_1 = y * 112 + x * 4;
    sum += input[base_1_1] * filterWeights[16];
    sum += input[base_1_1 + 1] * filterWeights[17];
    sum += input[base_1_1 + 2] * filterWeights[18];
    sum += input[base_1_1 + 3] * filterWeights[19];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 112 + (x + 1) * 4;
        sum += input[base_1_2] * filterWeights[20];
        sum += input[base_1_2 + 1] * filterWeights[21];
        sum += input[base_1_2 + 2] * filterWeights[22];
        sum += input[base_1_2 + 3] * filterWeights[23];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 112 + (x - 1) * 4;
        sum += input[base_2_0] * filterWeights[24];
        sum += input[base_2_0 + 1] * filterWeights[25];
        sum += input[base_2_0 + 2] * filterWeights[26];
        sum += input[base_2_0 + 3] * filterWeights[27];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 112 + x * 4;
        sum += input[base_2_1] * filterWeights[28];
        sum += input[base_2_1 + 1] * filterWeights[29];
        sum += input[base_2_1 + 2] * filterWeights[30];
        sum += input[base_2_1 + 3] * filterWeights[31];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 112 + (x + 1) * 4;
        sum += input[base_2_2] * filterWeights[32];
        sum += input[base_2_2 + 1] * filterWeights[33];
        sum += input[base_2_2 + 2] * filterWeights[34];
        sum += input[base_2_2 + 3] * filterWeights[35];
    }

    sum += bias[0];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c8_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=8 filterSize=3 filters=1
// dims: in 28x28x8 -> out 28x28x1 (output channels = 1) | weights [1][3][3][8] | bias [1]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c8_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 224 + (x - 1) * 8;
        sum += input[base_0_0] * filterWeights[0];
        sum += input[base_0_0 + 1] * filterWeights[1];
        sum += input[base_0_0 + 2] * filterWeights[2];
        sum += input[base_0_0 + 3] * filterWeights[3];
        sum += input[base_0_0 + 4] * filterWeights[4];
        sum += input[base_0_0 + 5] * filterWeights[5];
        sum += input[base_0_0 + 6] * filterWeights[6];
        sum += input[base_0_0 + 7] * filterWeights[7];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 224 + x * 8;
        sum += input[base_0_1] * filterWeights[8];
        sum += input[base_0_1 + 1] * filterWeights[9];
        sum += input[base_0_1 + 2] * filterWeights[10];
        sum += input[base_0_1 + 3] * filterWeights[11];
        sum += input[base_0_1 + 4] * filterWeights[12];
        sum += input[base_0_1 + 5] * filterWeights[13];
        sum += input[base_0_1 + 6] * filterWeights[14];
        sum += input[base_0_1 + 7] * filterWeights[15];
    }

    // tap (0, 2)
    if (y >= 1 && x < 27)
    {
        const int base_0_2 = (y - 1) * 224 + (x + 1) * 8;
        sum += input[base_0_2] * filterWeights[16];
        sum += input[base_0_2 + 1] * filterWeights[17];
        sum += input[base_0_2 + 2] * filterWeights[18];
        sum += input[base_0_2 + 3] * filterWeights[19];
        sum += input[base_0_2 + 4] * filterWeights[20];
        sum += input[base_0_2 + 5] * filterWeights[21];
        sum += input[base_0_2 + 6] * filterWeights[22];
        sum += input[base_0_2 + 7] * filterWeights[23];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 224 + (x - 1) * 8;
        sum += input[base_1_0] * filterWeights[24];
        sum += input[base_1_0 + 1] * filterWeights[25];
        sum += input[base_1_0 + 2] * filterWeights[26];
        sum += input[base_1_0 + 3] * filterWeights[27];
        sum += input[base_1_0 + 4] * filterWeights[28];
        sum += input[base_1_0 + 5] * filterWeights[29];
        sum += input[base_1_0 + 6] * filterWeights[30];
        sum += input[base_1_0 + 7] * filterWeights[31];
    }

    // tap (1, 1)
    const int base_1_1 = y * 224 + x * 8;
    sum += input[base_1_1] * filterWeights[32];
    sum += input[base_1_1 + 1] * filterWeights[33];
    sum += input[base_1_1 + 2] * filterWeights[34];
    sum += input[base_1_1 + 3] * filterWeights[35];
    sum += input[base_1_1 + 4] * filterWeights[36];
    sum += input[base_1_1 + 5] * filterWeights[37];
    sum += input[base_1_1 + 6] * filterWeights[38];
    sum += input[base_1_1 + 7] * filterWeights[39];

    // tap (1, 2)
    if (x < 27)
    {
        const int base_1_2 = y * 224 + (x + 1) * 8;
        sum += input[base_1_2] * filterWeights[40];
        sum += input[base_1_2 + 1] * filterWeights[41];
        sum += input[base_1_2 + 2] * filterWeights[42];
        sum += input[base_1_2 + 3] * filterWeights[43];
        sum += input[base_1_2 + 4] * filterWeights[44];
        sum += input[base_1_2 + 5] * filterWeights[45];
        sum += input[base_1_2 + 6] * filterWeights[46];
        sum += input[base_1_2 + 7] * filterWeights[47];
    }

    // tap (2, 0)
    if (y < 27 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 224 + (x - 1) * 8;
        sum += input[base_2_0] * filterWeights[48];
        sum += input[base_2_0 + 1] * filterWeights[49];
        sum += input[base_2_0 + 2] * filterWeights[50];
        sum += input[base_2_0 + 3] * filterWeights[51];
        sum += input[base_2_0 + 4] * filterWeights[52];
        sum += input[base_2_0 + 5] * filterWeights[53];
        sum += input[base_2_0 + 6] * filterWeights[54];
        sum += input[base_2_0 + 7] * filterWeights[55];
    }

    // tap (2, 1)
    if (y < 27)
    {
        const int base_2_1 = (y + 1) * 224 + x * 8;
        sum += input[base_2_1] * filterWeights[56];
        sum += input[base_2_1 + 1] * filterWeights[57];
        sum += input[base_2_1 + 2] * filterWeights[58];
        sum += input[base_2_1 + 3] * filterWeights[59];
        sum += input[base_2_1 + 4] * filterWeights[60];
        sum += input[base_2_1 + 5] * filterWeights[61];
        sum += input[base_2_1 + 6] * filterWeights[62];
        sum += input[base_2_1 + 7] * filterWeights[63];
    }

    // tap (2, 2)
    if (y < 27 && x < 27)
    {
        const int base_2_2 = (y + 1) * 224 + (x + 1) * 8;
        sum += input[base_2_2] * filterWeights[64];
        sum += input[base_2_2 + 1] * filterWeights[65];
        sum += input[base_2_2 + 2] * filterWeights[66];
        sum += input[base_2_2 + 3] * filterWeights[67];
        sum += input[base_2_2 + 4] * filterWeights[68];
        sum += input[base_2_2 + 5] * filterWeights[69];
        sum += input[base_2_2 + 6] * filterWeights[70];
        sum += input[base_2_2 + 7] * filterWeights[71];
    }

    sum += bias[0];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 28 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c1_f3 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=1 filterSize=3 filters=1
// dims: in 14x14x1 -> out 14x14x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c1_f3(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14) return;

    float sum = 0.0f;

    // tap (0, 0)
    if (y >= 1 && x >= 1)
    {
        const int base_0_0 = (y - 1) * 14 + (x - 1) * 1;
        sum += input[base_0_0] * filterWeights[0];
    }

    // tap (0, 1)
    if (y >= 1)
    {
        const int base_0_1 = (y - 1) * 14 + x * 1;
        sum += input[base_0_1] * filterWeights[1];
    }

    // tap (0, 2)
    if (y >= 1 && x < 13)
    {
        const int base_0_2 = (y - 1) * 14 + (x + 1) * 1;
        sum += input[base_0_2] * filterWeights[2];
    }

    // tap (1, 0)
    if (x >= 1)
    {
        const int base_1_0 = y * 14 + (x - 1) * 1;
        sum += input[base_1_0] * filterWeights[3];
    }

    // tap (1, 1)
    const int base_1_1 = y * 14 + x * 1;
    sum += input[base_1_1] * filterWeights[4];

    // tap (1, 2)
    if (x < 13)
    {
        const int base_1_2 = y * 14 + (x + 1) * 1;
        sum += input[base_1_2] * filterWeights[5];
    }

    // tap (2, 0)
    if (y < 13 && x >= 1)
    {
        const int base_2_0 = (y + 1) * 14 + (x - 1) * 1;
        sum += input[base_2_0] * filterWeights[6];
    }

    // tap (2, 1)
    if (y < 13)
    {
        const int base_2_1 = (y + 1) * 14 + x * 1;
        sum += input[base_2_1] * filterWeights[7];
    }

    // tap (2, 2)
    if (y < 13 && x < 13)
    {
        const int base_2_2 = (y + 1) * 14 + (x + 1) * 1;
        sum += input[base_2_2] * filterWeights[8];
    }

    sum += bias[0];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    const int idx = y * 14 + x;
    output[idx] = accumulate ? output[idx] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3_n4 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=4
// dims: in 28x28x1 -> out 28x28x4 (output channels = 4) | weights [4][3][3][1] | bias [4]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3_n4(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    for (int n = 0; n < 4; n++)
    {
        float sum = 0.0f;

        // tap (0, 0)
        if (y >= 1 && x >= 1)
        {
            const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
            sum += input[base_0_0] * filterWeights[n * 9 + 0];
        }

        // tap (0, 1)
        if (y >= 1)
        {
            const int base_0_1 = (y - 1) * 28 + x * 1;
            sum += input[base_0_1] * filterWeights[n * 9 + 1];
        }

        // tap (0, 2)
        if (y >= 1 && x < 27)
        {
            const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
            sum += input[base_0_2] * filterWeights[n * 9 + 2];
        }

        // tap (1, 0)
        if (x >= 1)
        {
            const int base_1_0 = y * 28 + (x - 1) * 1;
            sum += input[base_1_0] * filterWeights[n * 9 + 3];
        }

        // tap (1, 1)
        const int base_1_1 = y * 28 + x * 1;
        sum += input[base_1_1] * filterWeights[n * 9 + 4];

        // tap (1, 2)
        if (x < 27)
        {
            const int base_1_2 = y * 28 + (x + 1) * 1;
            sum += input[base_1_2] * filterWeights[n * 9 + 5];
        }

        // tap (2, 0)
        if (y < 27 && x >= 1)
        {
            const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
            sum += input[base_2_0] * filterWeights[n * 9 + 6];
        }

        // tap (2, 1)
        if (y < 27)
        {
            const int base_2_1 = (y + 1) * 28 + x * 1;
            sum += input[base_2_1] * filterWeights[n * 9 + 7];
        }

        // tap (2, 2)
        if (y < 27 && x < 27)
        {
            const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
            sum += input[base_2_2] * filterWeights[n * 9 + 8];
        }

        sum += bias[n];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 4 + n;
        output[idx] = accumulate ? output[idx] + value : value;
    }
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c4_f3_n4 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=4 filterSize=3 filters=4
// dims: in 14x14x4 -> out 14x14x4 (output channels = 4) | weights [4][3][3][4] | bias [4]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c4_f3_n4(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14) return;

    for (int n = 0; n < 4; n++)
    {
        float sum = 0.0f;

        // tap (0, 0)
        if (y >= 1 && x >= 1)
        {
            const int base_0_0 = (y - 1) * 56 + (x - 1) * 4;
            sum += input[base_0_0] * filterWeights[n * 36 + 0];
            sum += input[base_0_0 + 1] * filterWeights[n * 36 + 1];
            sum += input[base_0_0 + 2] * filterWeights[n * 36 + 2];
            sum += input[base_0_0 + 3] * filterWeights[n * 36 + 3];
        }

        // tap (0, 1)
        if (y >= 1)
        {
            const int base_0_1 = (y - 1) * 56 + x * 4;
            sum += input[base_0_1] * filterWeights[n * 36 + 4];
            sum += input[base_0_1 + 1] * filterWeights[n * 36 + 5];
            sum += input[base_0_1 + 2] * filterWeights[n * 36 + 6];
            sum += input[base_0_1 + 3] * filterWeights[n * 36 + 7];
        }

        // tap (0, 2)
        if (y >= 1 && x < 13)
        {
            const int base_0_2 = (y - 1) * 56 + (x + 1) * 4;
            sum += input[base_0_2] * filterWeights[n * 36 + 8];
            sum += input[base_0_2 + 1] * filterWeights[n * 36 + 9];
            sum += input[base_0_2 + 2] * filterWeights[n * 36 + 10];
            sum += input[base_0_2 + 3] * filterWeights[n * 36 + 11];
        }

        // tap (1, 0)
        if (x >= 1)
        {
            const int base_1_0 = y * 56 + (x - 1) * 4;
            sum += input[base_1_0] * filterWeights[n * 36 + 12];
            sum += input[base_1_0 + 1] * filterWeights[n * 36 + 13];
            sum += input[base_1_0 + 2] * filterWeights[n * 36 + 14];
            sum += input[base_1_0 + 3] * filterWeights[n * 36 + 15];
        }

        // tap (1, 1)
        const int base_1_1 = y * 56 + x * 4;
        sum += input[base_1_1] * filterWeights[n * 36 + 16];
        sum += input[base_1_1 + 1] * filterWeights[n * 36 + 17];
        sum += input[base_1_1 + 2] * filterWeights[n * 36 + 18];
        sum += input[base_1_1 + 3] * filterWeights[n * 36 + 19];

        // tap (1, 2)
        if (x < 13)
        {
            const int base_1_2 = y * 56 + (x + 1) * 4;
            sum += input[base_1_2] * filterWeights[n * 36 + 20];
            sum += input[base_1_2 + 1] * filterWeights[n * 36 + 21];
            sum += input[base_1_2 + 2] * filterWeights[n * 36 + 22];
            sum += input[base_1_2 + 3] * filterWeights[n * 36 + 23];
        }

        // tap (2, 0)
        if (y < 13 && x >= 1)
        {
            const int base_2_0 = (y + 1) * 56 + (x - 1) * 4;
            sum += input[base_2_0] * filterWeights[n * 36 + 24];
            sum += input[base_2_0 + 1] * filterWeights[n * 36 + 25];
            sum += input[base_2_0 + 2] * filterWeights[n * 36 + 26];
            sum += input[base_2_0 + 3] * filterWeights[n * 36 + 27];
        }

        // tap (2, 1)
        if (y < 13)
        {
            const int base_2_1 = (y + 1) * 56 + x * 4;
            sum += input[base_2_1] * filterWeights[n * 36 + 28];
            sum += input[base_2_1 + 1] * filterWeights[n * 36 + 29];
            sum += input[base_2_1 + 2] * filterWeights[n * 36 + 30];
            sum += input[base_2_1 + 3] * filterWeights[n * 36 + 31];
        }

        // tap (2, 2)
        if (y < 13 && x < 13)
        {
            const int base_2_2 = (y + 1) * 56 + (x + 1) * 4;
            sum += input[base_2_2] * filterWeights[n * 36 + 32];
            sum += input[base_2_2 + 1] * filterWeights[n * 36 + 33];
            sum += input[base_2_2 + 2] * filterWeights[n * 36 + 34];
            sum += input[base_2_2 + 3] * filterWeights[n * 36 + 35];
        }

        sum += bias[n];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 4 + n;
        output[idx] = accumulate ? output[idx] + value : value;
    }
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=1 poolSize=2 -> 14x14
// dims: in 28x28x1 -> out 14x14x1 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 28]);
    m0 = max(m0, input[base + 29]);
    output[(oy * 14 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c8_p4 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=8 poolSize=4 -> 7x7
// dims: in 28x28x8 -> out 7x7x8 (max pool 4x4, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c8_p4(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 4) * 28 + (ox * 4)) * 8;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 8]);
    m0 = max(m0, input[base + 16]);
    m0 = max(m0, input[base + 24]);
    m0 = max(m0, input[base + 224]);
    m0 = max(m0, input[base + 232]);
    m0 = max(m0, input[base + 240]);
    m0 = max(m0, input[base + 248]);
    m0 = max(m0, input[base + 448]);
    m0 = max(m0, input[base + 456]);
    m0 = max(m0, input[base + 464]);
    m0 = max(m0, input[base + 472]);
    m0 = max(m0, input[base + 672]);
    m0 = max(m0, input[base + 680]);
    m0 = max(m0, input[base + 688]);
    m0 = max(m0, input[base + 696]);
    output[(oy * 7 + ox) * 8 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 9]);
    m1 = max(m1, input[base + 17]);
    m1 = max(m1, input[base + 25]);
    m1 = max(m1, input[base + 225]);
    m1 = max(m1, input[base + 233]);
    m1 = max(m1, input[base + 241]);
    m1 = max(m1, input[base + 249]);
    m1 = max(m1, input[base + 449]);
    m1 = max(m1, input[base + 457]);
    m1 = max(m1, input[base + 465]);
    m1 = max(m1, input[base + 473]);
    m1 = max(m1, input[base + 673]);
    m1 = max(m1, input[base + 681]);
    m1 = max(m1, input[base + 689]);
    m1 = max(m1, input[base + 697]);
    output[(oy * 7 + ox) * 8 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 10]);
    m2 = max(m2, input[base + 18]);
    m2 = max(m2, input[base + 26]);
    m2 = max(m2, input[base + 226]);
    m2 = max(m2, input[base + 234]);
    m2 = max(m2, input[base + 242]);
    m2 = max(m2, input[base + 250]);
    m2 = max(m2, input[base + 450]);
    m2 = max(m2, input[base + 458]);
    m2 = max(m2, input[base + 466]);
    m2 = max(m2, input[base + 474]);
    m2 = max(m2, input[base + 674]);
    m2 = max(m2, input[base + 682]);
    m2 = max(m2, input[base + 690]);
    m2 = max(m2, input[base + 698]);
    output[(oy * 7 + ox) * 8 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 11]);
    m3 = max(m3, input[base + 19]);
    m3 = max(m3, input[base + 27]);
    m3 = max(m3, input[base + 227]);
    m3 = max(m3, input[base + 235]);
    m3 = max(m3, input[base + 243]);
    m3 = max(m3, input[base + 251]);
    m3 = max(m3, input[base + 451]);
    m3 = max(m3, input[base + 459]);
    m3 = max(m3, input[base + 467]);
    m3 = max(m3, input[base + 475]);
    m3 = max(m3, input[base + 675]);
    m3 = max(m3, input[base + 683]);
    m3 = max(m3, input[base + 691]);
    m3 = max(m3, input[base + 699]);
    output[(oy * 7 + ox) * 8 + 3] = m3;

    // channel 4
    float m4 = -INFINITY;
    m4 = max(m4, input[base + 4]);
    m4 = max(m4, input[base + 12]);
    m4 = max(m4, input[base + 20]);
    m4 = max(m4, input[base + 28]);
    m4 = max(m4, input[base + 228]);
    m4 = max(m4, input[base + 236]);
    m4 = max(m4, input[base + 244]);
    m4 = max(m4, input[base + 252]);
    m4 = max(m4, input[base + 452]);
    m4 = max(m4, input[base + 460]);
    m4 = max(m4, input[base + 468]);
    m4 = max(m4, input[base + 476]);
    m4 = max(m4, input[base + 676]);
    m4 = max(m4, input[base + 684]);
    m4 = max(m4, input[base + 692]);
    m4 = max(m4, input[base + 700]);
    output[(oy * 7 + ox) * 8 + 4] = m4;

    // channel 5
    float m5 = -INFINITY;
    m5 = max(m5, input[base + 5]);
    m5 = max(m5, input[base + 13]);
    m5 = max(m5, input[base + 21]);
    m5 = max(m5, input[base + 29]);
    m5 = max(m5, input[base + 229]);
    m5 = max(m5, input[base + 237]);
    m5 = max(m5, input[base + 245]);
    m5 = max(m5, input[base + 253]);
    m5 = max(m5, input[base + 453]);
    m5 = max(m5, input[base + 461]);
    m5 = max(m5, input[base + 469]);
    m5 = max(m5, input[base + 477]);
    m5 = max(m5, input[base + 677]);
    m5 = max(m5, input[base + 685]);
    m5 = max(m5, input[base + 693]);
    m5 = max(m5, input[base + 701]);
    output[(oy * 7 + ox) * 8 + 5] = m5;

    // channel 6
    float m6 = -INFINITY;
    m6 = max(m6, input[base + 6]);
    m6 = max(m6, input[base + 14]);
    m6 = max(m6, input[base + 22]);
    m6 = max(m6, input[base + 30]);
    m6 = max(m6, input[base + 230]);
    m6 = max(m6, input[base + 238]);
    m6 = max(m6, input[base + 246]);
    m6 = max(m6, input[base + 254]);
    m6 = max(m6, input[base + 454]);
    m6 = max(m6, input[base + 462]);
    m6 = max(m6, input[base + 470]);
    m6 = max(m6, input[base + 478]);
    m6 = max(m6, input[base + 678]);
    m6 = max(m6, input[base + 686]);
    m6 = max(m6, input[base + 694]);
    m6 = max(m6, input[base + 702]);
    output[(oy * 7 + ox) * 8 + 6] = m6;

    // channel 7
    float m7 = -INFINITY;
    m7 = max(m7, input[base + 7]);
    m7 = max(m7, input[base + 15]);
    m7 = max(m7, input[base + 23]);
    m7 = max(m7, input[base + 31]);
    m7 = max(m7, input[base + 231]);
    m7 = max(m7, input[base + 239]);
    m7 = max(m7, input[base + 247]);
    m7 = max(m7, input[base + 255]);
    m7 = max(m7, input[base + 455]);
    m7 = max(m7, input[base + 463]);
    m7 = max(m7, input[base + 471]);
    m7 = max(m7, input[base + 479]);
    m7 = max(m7, input[base + 679]);
    m7 = max(m7, input[base + 687]);
    m7 = max(m7, input[base + 695]);
    m7 = max(m7, input[base + 703]);
    output[(oy * 7 + ox) * 8 + 7] = m7;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=1 poolSize=2 -> 7x7
// dims: in 14x14x1 -> out 7x7x1 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c1_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 1;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 1]);
    m0 = max(m0, input[base + 14]);
    m0 = max(m0, input[base + 15]);
    output[(oy * 7 + ox) * 1 + 0] = m0;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=4 poolSize=2 -> 14x14
// dims: in 28x28x4 -> out 14x14x4 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c4_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 4;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 4]);
    m0 = max(m0, input[base + 112]);
    m0 = max(m0, input[base + 116]);
    output[(oy * 14 + ox) * 4 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 5]);
    m1 = max(m1, input[base + 113]);
    m1 = max(m1, input[base + 117]);
    output[(oy * 14 + ox) * 4 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 6]);
    m2 = max(m2, input[base + 114]);
    m2 = max(m2, input[base + 118]);
    output[(oy * 14 + ox) * 4 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 7]);
    m3 = max(m3, input[base + 115]);
    m3 = max(m3, input[base + 119]);
    output[(oy * 14 + ox) * 4 + 3] = m3;

}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=4 poolSize=2 -> 7x7
// dims: in 14x14x4 -> out 7x7x4 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c4_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 4;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 4]);
    m0 = max(m0, input[base + 56]);
    m0 = max(m0, input[base + 60]);
    output[(oy * 7 + ox) * 4 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 5]);
    m1 = max(m1, input[base + 57]);
    m1 = max(m1, input[base + 61]);
    output[(oy * 7 + ox) * 4 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 6]);
    m2 = max(m2, input[base + 58]);
    m2 = max(m2, input[base + 62]);
    output[(oy * 7 + ox) * 4 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 7]);
    m3 = max(m3, input[base + 59]);
    m3 = max(m3, input[base + 63]);
    output[(oy * 7 + ox) * 4 + 3] = m3;

}

// ---------------------------------------------------------------------------
// cnn2dDense_i196_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=196 outputFloats=10
// dims: in 196 -> out 10 | weights [10][196] | bias [10]
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i196_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 196; i++)
        sum += input[i] * weights[o * 196 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i49_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=49 outputFloats=10
// dims: in 49 -> out 10 | weights [10][49] | bias [10]
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i49_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 49; i++)
        sum += input[i] * weights[o * 49 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dSoftmax_n10 -- generated by generateKernel.py (do not edit by hand)
// count=10 (softmax over the whole vector)
// dims: in 10 -> out 10 (probability distribution, sums to 1)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dSoftmax_n10(
    __global const float* input,
    __global float* output)
{
    if (get_global_id(0) != 0) return;

    float m = -INFINITY;
    for (int i = 0; i < 10; i++)
        m = max(m, input[i]);

    float s = 0.0f;
    for (int i = 0; i < 10; i++)
        s += exp(input[i] - m);

    for (int i = 0; i < 10; i++)
        output[i] = exp(input[i] - m) / s;
}

// ---------------------------------------------------------------------------
// cnn2dFilter_w28_h28_c1_f3_n16 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=28 height=28 channels=1 filterSize=3 filters=16
// dims: in 28x28x1 -> out 28x28x16 (output channels = 16) | weights [16][3][3][1] | bias [16]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w28_h28_c1_f3_n16(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 28 || y >= 28) return;

    for (int n = 0; n < 16; n++)
    {
        float sum = 0.0f;

        // tap (0, 0)
        if (y >= 1 && x >= 1)
        {
            const int base_0_0 = (y - 1) * 28 + (x - 1) * 1;
            sum += input[base_0_0] * filterWeights[n * 9 + 0];
        }

        // tap (0, 1)
        if (y >= 1)
        {
            const int base_0_1 = (y - 1) * 28 + x * 1;
            sum += input[base_0_1] * filterWeights[n * 9 + 1];
        }

        // tap (0, 2)
        if (y >= 1 && x < 27)
        {
            const int base_0_2 = (y - 1) * 28 + (x + 1) * 1;
            sum += input[base_0_2] * filterWeights[n * 9 + 2];
        }

        // tap (1, 0)
        if (x >= 1)
        {
            const int base_1_0 = y * 28 + (x - 1) * 1;
            sum += input[base_1_0] * filterWeights[n * 9 + 3];
        }

        // tap (1, 1)
        const int base_1_1 = y * 28 + x * 1;
        sum += input[base_1_1] * filterWeights[n * 9 + 4];

        // tap (1, 2)
        if (x < 27)
        {
            const int base_1_2 = y * 28 + (x + 1) * 1;
            sum += input[base_1_2] * filterWeights[n * 9 + 5];
        }

        // tap (2, 0)
        if (y < 27 && x >= 1)
        {
            const int base_2_0 = (y + 1) * 28 + (x - 1) * 1;
            sum += input[base_2_0] * filterWeights[n * 9 + 6];
        }

        // tap (2, 1)
        if (y < 27)
        {
            const int base_2_1 = (y + 1) * 28 + x * 1;
            sum += input[base_2_1] * filterWeights[n * 9 + 7];
        }

        // tap (2, 2)
        if (y < 27 && x < 27)
        {
            const int base_2_2 = (y + 1) * 28 + (x + 1) * 1;
            sum += input[base_2_2] * filterWeights[n * 9 + 8];
        }

        sum += bias[n];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 28 + x) * 16 + n;
        output[idx] = accumulate ? output[idx] + value : value;
    }
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w28_h28_c16_p2 -- generated by generateKernel.py (do not edit by hand)
// width=28 height=28 channels=16 poolSize=2 -> 14x14
// dims: in 28x28x16 -> out 14x14x16 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w28_h28_c16_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 14 || oy >= 14) return;

    const int base = ((oy * 2) * 28 + (ox * 2)) * 16;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 16]);
    m0 = max(m0, input[base + 448]);
    m0 = max(m0, input[base + 464]);
    output[(oy * 14 + ox) * 16 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 17]);
    m1 = max(m1, input[base + 449]);
    m1 = max(m1, input[base + 465]);
    output[(oy * 14 + ox) * 16 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 18]);
    m2 = max(m2, input[base + 450]);
    m2 = max(m2, input[base + 466]);
    output[(oy * 14 + ox) * 16 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 19]);
    m3 = max(m3, input[base + 451]);
    m3 = max(m3, input[base + 467]);
    output[(oy * 14 + ox) * 16 + 3] = m3;

    // channel 4
    float m4 = -INFINITY;
    m4 = max(m4, input[base + 4]);
    m4 = max(m4, input[base + 20]);
    m4 = max(m4, input[base + 452]);
    m4 = max(m4, input[base + 468]);
    output[(oy * 14 + ox) * 16 + 4] = m4;

    // channel 5
    float m5 = -INFINITY;
    m5 = max(m5, input[base + 5]);
    m5 = max(m5, input[base + 21]);
    m5 = max(m5, input[base + 453]);
    m5 = max(m5, input[base + 469]);
    output[(oy * 14 + ox) * 16 + 5] = m5;

    // channel 6
    float m6 = -INFINITY;
    m6 = max(m6, input[base + 6]);
    m6 = max(m6, input[base + 22]);
    m6 = max(m6, input[base + 454]);
    m6 = max(m6, input[base + 470]);
    output[(oy * 14 + ox) * 16 + 6] = m6;

    // channel 7
    float m7 = -INFINITY;
    m7 = max(m7, input[base + 7]);
    m7 = max(m7, input[base + 23]);
    m7 = max(m7, input[base + 455]);
    m7 = max(m7, input[base + 471]);
    output[(oy * 14 + ox) * 16 + 7] = m7;

    // channel 8
    float m8 = -INFINITY;
    m8 = max(m8, input[base + 8]);
    m8 = max(m8, input[base + 24]);
    m8 = max(m8, input[base + 456]);
    m8 = max(m8, input[base + 472]);
    output[(oy * 14 + ox) * 16 + 8] = m8;

    // channel 9
    float m9 = -INFINITY;
    m9 = max(m9, input[base + 9]);
    m9 = max(m9, input[base + 25]);
    m9 = max(m9, input[base + 457]);
    m9 = max(m9, input[base + 473]);
    output[(oy * 14 + ox) * 16 + 9] = m9;

    // channel 10
    float m10 = -INFINITY;
    m10 = max(m10, input[base + 10]);
    m10 = max(m10, input[base + 26]);
    m10 = max(m10, input[base + 458]);
    m10 = max(m10, input[base + 474]);
    output[(oy * 14 + ox) * 16 + 10] = m10;

    // channel 11
    float m11 = -INFINITY;
    m11 = max(m11, input[base + 11]);
    m11 = max(m11, input[base + 27]);
    m11 = max(m11, input[base + 459]);
    m11 = max(m11, input[base + 475]);
    output[(oy * 14 + ox) * 16 + 11] = m11;

    // channel 12
    float m12 = -INFINITY;
    m12 = max(m12, input[base + 12]);
    m12 = max(m12, input[base + 28]);
    m12 = max(m12, input[base + 460]);
    m12 = max(m12, input[base + 476]);
    output[(oy * 14 + ox) * 16 + 12] = m12;

    // channel 13
    float m13 = -INFINITY;
    m13 = max(m13, input[base + 13]);
    m13 = max(m13, input[base + 29]);
    m13 = max(m13, input[base + 461]);
    m13 = max(m13, input[base + 477]);
    output[(oy * 14 + ox) * 16 + 13] = m13;

    // channel 14
    float m14 = -INFINITY;
    m14 = max(m14, input[base + 14]);
    m14 = max(m14, input[base + 30]);
    m14 = max(m14, input[base + 462]);
    m14 = max(m14, input[base + 478]);
    output[(oy * 14 + ox) * 16 + 14] = m14;

    // channel 15
    float m15 = -INFINITY;
    m15 = max(m15, input[base + 15]);
    m15 = max(m15, input[base + 31]);
    m15 = max(m15, input[base + 463]);
    m15 = max(m15, input[base + 479]);
    output[(oy * 14 + ox) * 16 + 15] = m15;

}

// ---------------------------------------------------------------------------
// cnn2dFilter_w14_h14_c16_f3_n32 -- generated by generateKernel.py (kernelGen v2, do not edit by hand)
// width=14 height=14 channels=16 filterSize=3 filters=32
// dims: in 14x14x16 -> out 14x14x32 (output channels = 32) | weights [32][3][3][16] | bias [32]
// params: input, filterWeights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dFilter_w14_h14_c16_f3_n32(
    __global const float* input,
    __global const float* filterWeights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int x = get_global_id(0);
    const int y = get_global_id(1);
    if (x >= 14 || y >= 14) return;

    for (int n = 0; n < 32; n++)
    {
        float sum = 0.0f;

        // tap (0, 0)
        if (y >= 1 && x >= 1)
        {
            const int base_0_0 = (y - 1) * 224 + (x - 1) * 16;
            sum += input[base_0_0] * filterWeights[n * 144 + 0];
            sum += input[base_0_0 + 1] * filterWeights[n * 144 + 1];
            sum += input[base_0_0 + 2] * filterWeights[n * 144 + 2];
            sum += input[base_0_0 + 3] * filterWeights[n * 144 + 3];
            sum += input[base_0_0 + 4] * filterWeights[n * 144 + 4];
            sum += input[base_0_0 + 5] * filterWeights[n * 144 + 5];
            sum += input[base_0_0 + 6] * filterWeights[n * 144 + 6];
            sum += input[base_0_0 + 7] * filterWeights[n * 144 + 7];
            sum += input[base_0_0 + 8] * filterWeights[n * 144 + 8];
            sum += input[base_0_0 + 9] * filterWeights[n * 144 + 9];
            sum += input[base_0_0 + 10] * filterWeights[n * 144 + 10];
            sum += input[base_0_0 + 11] * filterWeights[n * 144 + 11];
            sum += input[base_0_0 + 12] * filterWeights[n * 144 + 12];
            sum += input[base_0_0 + 13] * filterWeights[n * 144 + 13];
            sum += input[base_0_0 + 14] * filterWeights[n * 144 + 14];
            sum += input[base_0_0 + 15] * filterWeights[n * 144 + 15];
        }

        // tap (0, 1)
        if (y >= 1)
        {
            const int base_0_1 = (y - 1) * 224 + x * 16;
            sum += input[base_0_1] * filterWeights[n * 144 + 16];
            sum += input[base_0_1 + 1] * filterWeights[n * 144 + 17];
            sum += input[base_0_1 + 2] * filterWeights[n * 144 + 18];
            sum += input[base_0_1 + 3] * filterWeights[n * 144 + 19];
            sum += input[base_0_1 + 4] * filterWeights[n * 144 + 20];
            sum += input[base_0_1 + 5] * filterWeights[n * 144 + 21];
            sum += input[base_0_1 + 6] * filterWeights[n * 144 + 22];
            sum += input[base_0_1 + 7] * filterWeights[n * 144 + 23];
            sum += input[base_0_1 + 8] * filterWeights[n * 144 + 24];
            sum += input[base_0_1 + 9] * filterWeights[n * 144 + 25];
            sum += input[base_0_1 + 10] * filterWeights[n * 144 + 26];
            sum += input[base_0_1 + 11] * filterWeights[n * 144 + 27];
            sum += input[base_0_1 + 12] * filterWeights[n * 144 + 28];
            sum += input[base_0_1 + 13] * filterWeights[n * 144 + 29];
            sum += input[base_0_1 + 14] * filterWeights[n * 144 + 30];
            sum += input[base_0_1 + 15] * filterWeights[n * 144 + 31];
        }

        // tap (0, 2)
        if (y >= 1 && x < 13)
        {
            const int base_0_2 = (y - 1) * 224 + (x + 1) * 16;
            sum += input[base_0_2] * filterWeights[n * 144 + 32];
            sum += input[base_0_2 + 1] * filterWeights[n * 144 + 33];
            sum += input[base_0_2 + 2] * filterWeights[n * 144 + 34];
            sum += input[base_0_2 + 3] * filterWeights[n * 144 + 35];
            sum += input[base_0_2 + 4] * filterWeights[n * 144 + 36];
            sum += input[base_0_2 + 5] * filterWeights[n * 144 + 37];
            sum += input[base_0_2 + 6] * filterWeights[n * 144 + 38];
            sum += input[base_0_2 + 7] * filterWeights[n * 144 + 39];
            sum += input[base_0_2 + 8] * filterWeights[n * 144 + 40];
            sum += input[base_0_2 + 9] * filterWeights[n * 144 + 41];
            sum += input[base_0_2 + 10] * filterWeights[n * 144 + 42];
            sum += input[base_0_2 + 11] * filterWeights[n * 144 + 43];
            sum += input[base_0_2 + 12] * filterWeights[n * 144 + 44];
            sum += input[base_0_2 + 13] * filterWeights[n * 144 + 45];
            sum += input[base_0_2 + 14] * filterWeights[n * 144 + 46];
            sum += input[base_0_2 + 15] * filterWeights[n * 144 + 47];
        }

        // tap (1, 0)
        if (x >= 1)
        {
            const int base_1_0 = y * 224 + (x - 1) * 16;
            sum += input[base_1_0] * filterWeights[n * 144 + 48];
            sum += input[base_1_0 + 1] * filterWeights[n * 144 + 49];
            sum += input[base_1_0 + 2] * filterWeights[n * 144 + 50];
            sum += input[base_1_0 + 3] * filterWeights[n * 144 + 51];
            sum += input[base_1_0 + 4] * filterWeights[n * 144 + 52];
            sum += input[base_1_0 + 5] * filterWeights[n * 144 + 53];
            sum += input[base_1_0 + 6] * filterWeights[n * 144 + 54];
            sum += input[base_1_0 + 7] * filterWeights[n * 144 + 55];
            sum += input[base_1_0 + 8] * filterWeights[n * 144 + 56];
            sum += input[base_1_0 + 9] * filterWeights[n * 144 + 57];
            sum += input[base_1_0 + 10] * filterWeights[n * 144 + 58];
            sum += input[base_1_0 + 11] * filterWeights[n * 144 + 59];
            sum += input[base_1_0 + 12] * filterWeights[n * 144 + 60];
            sum += input[base_1_0 + 13] * filterWeights[n * 144 + 61];
            sum += input[base_1_0 + 14] * filterWeights[n * 144 + 62];
            sum += input[base_1_0 + 15] * filterWeights[n * 144 + 63];
        }

        // tap (1, 1)
        const int base_1_1 = y * 224 + x * 16;
        sum += input[base_1_1] * filterWeights[n * 144 + 64];
        sum += input[base_1_1 + 1] * filterWeights[n * 144 + 65];
        sum += input[base_1_1 + 2] * filterWeights[n * 144 + 66];
        sum += input[base_1_1 + 3] * filterWeights[n * 144 + 67];
        sum += input[base_1_1 + 4] * filterWeights[n * 144 + 68];
        sum += input[base_1_1 + 5] * filterWeights[n * 144 + 69];
        sum += input[base_1_1 + 6] * filterWeights[n * 144 + 70];
        sum += input[base_1_1 + 7] * filterWeights[n * 144 + 71];
        sum += input[base_1_1 + 8] * filterWeights[n * 144 + 72];
        sum += input[base_1_1 + 9] * filterWeights[n * 144 + 73];
        sum += input[base_1_1 + 10] * filterWeights[n * 144 + 74];
        sum += input[base_1_1 + 11] * filterWeights[n * 144 + 75];
        sum += input[base_1_1 + 12] * filterWeights[n * 144 + 76];
        sum += input[base_1_1 + 13] * filterWeights[n * 144 + 77];
        sum += input[base_1_1 + 14] * filterWeights[n * 144 + 78];
        sum += input[base_1_1 + 15] * filterWeights[n * 144 + 79];

        // tap (1, 2)
        if (x < 13)
        {
            const int base_1_2 = y * 224 + (x + 1) * 16;
            sum += input[base_1_2] * filterWeights[n * 144 + 80];
            sum += input[base_1_2 + 1] * filterWeights[n * 144 + 81];
            sum += input[base_1_2 + 2] * filterWeights[n * 144 + 82];
            sum += input[base_1_2 + 3] * filterWeights[n * 144 + 83];
            sum += input[base_1_2 + 4] * filterWeights[n * 144 + 84];
            sum += input[base_1_2 + 5] * filterWeights[n * 144 + 85];
            sum += input[base_1_2 + 6] * filterWeights[n * 144 + 86];
            sum += input[base_1_2 + 7] * filterWeights[n * 144 + 87];
            sum += input[base_1_2 + 8] * filterWeights[n * 144 + 88];
            sum += input[base_1_2 + 9] * filterWeights[n * 144 + 89];
            sum += input[base_1_2 + 10] * filterWeights[n * 144 + 90];
            sum += input[base_1_2 + 11] * filterWeights[n * 144 + 91];
            sum += input[base_1_2 + 12] * filterWeights[n * 144 + 92];
            sum += input[base_1_2 + 13] * filterWeights[n * 144 + 93];
            sum += input[base_1_2 + 14] * filterWeights[n * 144 + 94];
            sum += input[base_1_2 + 15] * filterWeights[n * 144 + 95];
        }

        // tap (2, 0)
        if (y < 13 && x >= 1)
        {
            const int base_2_0 = (y + 1) * 224 + (x - 1) * 16;
            sum += input[base_2_0] * filterWeights[n * 144 + 96];
            sum += input[base_2_0 + 1] * filterWeights[n * 144 + 97];
            sum += input[base_2_0 + 2] * filterWeights[n * 144 + 98];
            sum += input[base_2_0 + 3] * filterWeights[n * 144 + 99];
            sum += input[base_2_0 + 4] * filterWeights[n * 144 + 100];
            sum += input[base_2_0 + 5] * filterWeights[n * 144 + 101];
            sum += input[base_2_0 + 6] * filterWeights[n * 144 + 102];
            sum += input[base_2_0 + 7] * filterWeights[n * 144 + 103];
            sum += input[base_2_0 + 8] * filterWeights[n * 144 + 104];
            sum += input[base_2_0 + 9] * filterWeights[n * 144 + 105];
            sum += input[base_2_0 + 10] * filterWeights[n * 144 + 106];
            sum += input[base_2_0 + 11] * filterWeights[n * 144 + 107];
            sum += input[base_2_0 + 12] * filterWeights[n * 144 + 108];
            sum += input[base_2_0 + 13] * filterWeights[n * 144 + 109];
            sum += input[base_2_0 + 14] * filterWeights[n * 144 + 110];
            sum += input[base_2_0 + 15] * filterWeights[n * 144 + 111];
        }

        // tap (2, 1)
        if (y < 13)
        {
            const int base_2_1 = (y + 1) * 224 + x * 16;
            sum += input[base_2_1] * filterWeights[n * 144 + 112];
            sum += input[base_2_1 + 1] * filterWeights[n * 144 + 113];
            sum += input[base_2_1 + 2] * filterWeights[n * 144 + 114];
            sum += input[base_2_1 + 3] * filterWeights[n * 144 + 115];
            sum += input[base_2_1 + 4] * filterWeights[n * 144 + 116];
            sum += input[base_2_1 + 5] * filterWeights[n * 144 + 117];
            sum += input[base_2_1 + 6] * filterWeights[n * 144 + 118];
            sum += input[base_2_1 + 7] * filterWeights[n * 144 + 119];
            sum += input[base_2_1 + 8] * filterWeights[n * 144 + 120];
            sum += input[base_2_1 + 9] * filterWeights[n * 144 + 121];
            sum += input[base_2_1 + 10] * filterWeights[n * 144 + 122];
            sum += input[base_2_1 + 11] * filterWeights[n * 144 + 123];
            sum += input[base_2_1 + 12] * filterWeights[n * 144 + 124];
            sum += input[base_2_1 + 13] * filterWeights[n * 144 + 125];
            sum += input[base_2_1 + 14] * filterWeights[n * 144 + 126];
            sum += input[base_2_1 + 15] * filterWeights[n * 144 + 127];
        }

        // tap (2, 2)
        if (y < 13 && x < 13)
        {
            const int base_2_2 = (y + 1) * 224 + (x + 1) * 16;
            sum += input[base_2_2] * filterWeights[n * 144 + 128];
            sum += input[base_2_2 + 1] * filterWeights[n * 144 + 129];
            sum += input[base_2_2 + 2] * filterWeights[n * 144 + 130];
            sum += input[base_2_2 + 3] * filterWeights[n * 144 + 131];
            sum += input[base_2_2 + 4] * filterWeights[n * 144 + 132];
            sum += input[base_2_2 + 5] * filterWeights[n * 144 + 133];
            sum += input[base_2_2 + 6] * filterWeights[n * 144 + 134];
            sum += input[base_2_2 + 7] * filterWeights[n * 144 + 135];
            sum += input[base_2_2 + 8] * filterWeights[n * 144 + 136];
            sum += input[base_2_2 + 9] * filterWeights[n * 144 + 137];
            sum += input[base_2_2 + 10] * filterWeights[n * 144 + 138];
            sum += input[base_2_2 + 11] * filterWeights[n * 144 + 139];
            sum += input[base_2_2 + 12] * filterWeights[n * 144 + 140];
            sum += input[base_2_2 + 13] * filterWeights[n * 144 + 141];
            sum += input[base_2_2 + 14] * filterWeights[n * 144 + 142];
            sum += input[base_2_2 + 15] * filterWeights[n * 144 + 143];
        }

        sum += bias[n];

        float value = sum;
        switch (activation)
        {
            case ReLU:    value = max(sum, 0.0f); break;
            case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
            case Tanh:    value = tanh(sum); break;
            case None:    value = sum; break;
        }

        const int idx = (y * 14 + x) * 32 + n;
        output[idx] = accumulate ? output[idx] + value : value;
    }
}

// ---------------------------------------------------------------------------
// cnn2dMaxPool_w14_h14_c32_p2 -- generated by generateKernel.py (do not edit by hand)
// width=14 height=14 channels=32 poolSize=2 -> 7x7
// dims: in 14x14x32 -> out 7x7x32 (max pool 2x2, per channel)
// params: input, output
// ---------------------------------------------------------------------------
__kernel void cnn2dMaxPool_w14_h14_c32_p2(
    __global const float* input,
    __global float* output)
{
    const int ox = get_global_id(0);
    const int oy = get_global_id(1);
    if (ox >= 7 || oy >= 7) return;

    const int base = ((oy * 2) * 14 + (ox * 2)) * 32;

    // channel 0
    float m0 = -INFINITY;
    m0 = max(m0, input[base]);
    m0 = max(m0, input[base + 32]);
    m0 = max(m0, input[base + 448]);
    m0 = max(m0, input[base + 480]);
    output[(oy * 7 + ox) * 32 + 0] = m0;

    // channel 1
    float m1 = -INFINITY;
    m1 = max(m1, input[base + 1]);
    m1 = max(m1, input[base + 33]);
    m1 = max(m1, input[base + 449]);
    m1 = max(m1, input[base + 481]);
    output[(oy * 7 + ox) * 32 + 1] = m1;

    // channel 2
    float m2 = -INFINITY;
    m2 = max(m2, input[base + 2]);
    m2 = max(m2, input[base + 34]);
    m2 = max(m2, input[base + 450]);
    m2 = max(m2, input[base + 482]);
    output[(oy * 7 + ox) * 32 + 2] = m2;

    // channel 3
    float m3 = -INFINITY;
    m3 = max(m3, input[base + 3]);
    m3 = max(m3, input[base + 35]);
    m3 = max(m3, input[base + 451]);
    m3 = max(m3, input[base + 483]);
    output[(oy * 7 + ox) * 32 + 3] = m3;

    // channel 4
    float m4 = -INFINITY;
    m4 = max(m4, input[base + 4]);
    m4 = max(m4, input[base + 36]);
    m4 = max(m4, input[base + 452]);
    m4 = max(m4, input[base + 484]);
    output[(oy * 7 + ox) * 32 + 4] = m4;

    // channel 5
    float m5 = -INFINITY;
    m5 = max(m5, input[base + 5]);
    m5 = max(m5, input[base + 37]);
    m5 = max(m5, input[base + 453]);
    m5 = max(m5, input[base + 485]);
    output[(oy * 7 + ox) * 32 + 5] = m5;

    // channel 6
    float m6 = -INFINITY;
    m6 = max(m6, input[base + 6]);
    m6 = max(m6, input[base + 38]);
    m6 = max(m6, input[base + 454]);
    m6 = max(m6, input[base + 486]);
    output[(oy * 7 + ox) * 32 + 6] = m6;

    // channel 7
    float m7 = -INFINITY;
    m7 = max(m7, input[base + 7]);
    m7 = max(m7, input[base + 39]);
    m7 = max(m7, input[base + 455]);
    m7 = max(m7, input[base + 487]);
    output[(oy * 7 + ox) * 32 + 7] = m7;

    // channel 8
    float m8 = -INFINITY;
    m8 = max(m8, input[base + 8]);
    m8 = max(m8, input[base + 40]);
    m8 = max(m8, input[base + 456]);
    m8 = max(m8, input[base + 488]);
    output[(oy * 7 + ox) * 32 + 8] = m8;

    // channel 9
    float m9 = -INFINITY;
    m9 = max(m9, input[base + 9]);
    m9 = max(m9, input[base + 41]);
    m9 = max(m9, input[base + 457]);
    m9 = max(m9, input[base + 489]);
    output[(oy * 7 + ox) * 32 + 9] = m9;

    // channel 10
    float m10 = -INFINITY;
    m10 = max(m10, input[base + 10]);
    m10 = max(m10, input[base + 42]);
    m10 = max(m10, input[base + 458]);
    m10 = max(m10, input[base + 490]);
    output[(oy * 7 + ox) * 32 + 10] = m10;

    // channel 11
    float m11 = -INFINITY;
    m11 = max(m11, input[base + 11]);
    m11 = max(m11, input[base + 43]);
    m11 = max(m11, input[base + 459]);
    m11 = max(m11, input[base + 491]);
    output[(oy * 7 + ox) * 32 + 11] = m11;

    // channel 12
    float m12 = -INFINITY;
    m12 = max(m12, input[base + 12]);
    m12 = max(m12, input[base + 44]);
    m12 = max(m12, input[base + 460]);
    m12 = max(m12, input[base + 492]);
    output[(oy * 7 + ox) * 32 + 12] = m12;

    // channel 13
    float m13 = -INFINITY;
    m13 = max(m13, input[base + 13]);
    m13 = max(m13, input[base + 45]);
    m13 = max(m13, input[base + 461]);
    m13 = max(m13, input[base + 493]);
    output[(oy * 7 + ox) * 32 + 13] = m13;

    // channel 14
    float m14 = -INFINITY;
    m14 = max(m14, input[base + 14]);
    m14 = max(m14, input[base + 46]);
    m14 = max(m14, input[base + 462]);
    m14 = max(m14, input[base + 494]);
    output[(oy * 7 + ox) * 32 + 14] = m14;

    // channel 15
    float m15 = -INFINITY;
    m15 = max(m15, input[base + 15]);
    m15 = max(m15, input[base + 47]);
    m15 = max(m15, input[base + 463]);
    m15 = max(m15, input[base + 495]);
    output[(oy * 7 + ox) * 32 + 15] = m15;

    // channel 16
    float m16 = -INFINITY;
    m16 = max(m16, input[base + 16]);
    m16 = max(m16, input[base + 48]);
    m16 = max(m16, input[base + 464]);
    m16 = max(m16, input[base + 496]);
    output[(oy * 7 + ox) * 32 + 16] = m16;

    // channel 17
    float m17 = -INFINITY;
    m17 = max(m17, input[base + 17]);
    m17 = max(m17, input[base + 49]);
    m17 = max(m17, input[base + 465]);
    m17 = max(m17, input[base + 497]);
    output[(oy * 7 + ox) * 32 + 17] = m17;

    // channel 18
    float m18 = -INFINITY;
    m18 = max(m18, input[base + 18]);
    m18 = max(m18, input[base + 50]);
    m18 = max(m18, input[base + 466]);
    m18 = max(m18, input[base + 498]);
    output[(oy * 7 + ox) * 32 + 18] = m18;

    // channel 19
    float m19 = -INFINITY;
    m19 = max(m19, input[base + 19]);
    m19 = max(m19, input[base + 51]);
    m19 = max(m19, input[base + 467]);
    m19 = max(m19, input[base + 499]);
    output[(oy * 7 + ox) * 32 + 19] = m19;

    // channel 20
    float m20 = -INFINITY;
    m20 = max(m20, input[base + 20]);
    m20 = max(m20, input[base + 52]);
    m20 = max(m20, input[base + 468]);
    m20 = max(m20, input[base + 500]);
    output[(oy * 7 + ox) * 32 + 20] = m20;

    // channel 21
    float m21 = -INFINITY;
    m21 = max(m21, input[base + 21]);
    m21 = max(m21, input[base + 53]);
    m21 = max(m21, input[base + 469]);
    m21 = max(m21, input[base + 501]);
    output[(oy * 7 + ox) * 32 + 21] = m21;

    // channel 22
    float m22 = -INFINITY;
    m22 = max(m22, input[base + 22]);
    m22 = max(m22, input[base + 54]);
    m22 = max(m22, input[base + 470]);
    m22 = max(m22, input[base + 502]);
    output[(oy * 7 + ox) * 32 + 22] = m22;

    // channel 23
    float m23 = -INFINITY;
    m23 = max(m23, input[base + 23]);
    m23 = max(m23, input[base + 55]);
    m23 = max(m23, input[base + 471]);
    m23 = max(m23, input[base + 503]);
    output[(oy * 7 + ox) * 32 + 23] = m23;

    // channel 24
    float m24 = -INFINITY;
    m24 = max(m24, input[base + 24]);
    m24 = max(m24, input[base + 56]);
    m24 = max(m24, input[base + 472]);
    m24 = max(m24, input[base + 504]);
    output[(oy * 7 + ox) * 32 + 24] = m24;

    // channel 25
    float m25 = -INFINITY;
    m25 = max(m25, input[base + 25]);
    m25 = max(m25, input[base + 57]);
    m25 = max(m25, input[base + 473]);
    m25 = max(m25, input[base + 505]);
    output[(oy * 7 + ox) * 32 + 25] = m25;

    // channel 26
    float m26 = -INFINITY;
    m26 = max(m26, input[base + 26]);
    m26 = max(m26, input[base + 58]);
    m26 = max(m26, input[base + 474]);
    m26 = max(m26, input[base + 506]);
    output[(oy * 7 + ox) * 32 + 26] = m26;

    // channel 27
    float m27 = -INFINITY;
    m27 = max(m27, input[base + 27]);
    m27 = max(m27, input[base + 59]);
    m27 = max(m27, input[base + 475]);
    m27 = max(m27, input[base + 507]);
    output[(oy * 7 + ox) * 32 + 27] = m27;

    // channel 28
    float m28 = -INFINITY;
    m28 = max(m28, input[base + 28]);
    m28 = max(m28, input[base + 60]);
    m28 = max(m28, input[base + 476]);
    m28 = max(m28, input[base + 508]);
    output[(oy * 7 + ox) * 32 + 28] = m28;

    // channel 29
    float m29 = -INFINITY;
    m29 = max(m29, input[base + 29]);
    m29 = max(m29, input[base + 61]);
    m29 = max(m29, input[base + 477]);
    m29 = max(m29, input[base + 509]);
    output[(oy * 7 + ox) * 32 + 29] = m29;

    // channel 30
    float m30 = -INFINITY;
    m30 = max(m30, input[base + 30]);
    m30 = max(m30, input[base + 62]);
    m30 = max(m30, input[base + 478]);
    m30 = max(m30, input[base + 510]);
    output[(oy * 7 + ox) * 32 + 30] = m30;

    // channel 31
    float m31 = -INFINITY;
    m31 = max(m31, input[base + 31]);
    m31 = max(m31, input[base + 63]);
    m31 = max(m31, input[base + 479]);
    m31 = max(m31, input[base + 511]);
    output[(oy * 7 + ox) * 32 + 31] = m31;

}

// ---------------------------------------------------------------------------
// cnn2dDense_i1568_o128 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=1568 outputFloats=128
// dims: in 1568 -> out 128 | weights [128][1568] | bias [128]
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i1568_o128(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 128) return;

    float sum = 0.0f;
    for (int i = 0; i < 1568; i++)
        sum += input[i] * weights[o * 1568 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}

// ---------------------------------------------------------------------------
// cnn2dDense_i128_o10 -- generated by generateKernel.py (do not edit by hand)
// inputFloats=128 outputFloats=10
// dims: in 128 -> out 10 | weights [10][128] | bias [10]
// params: input, weights, bias, output, activation, accumulate
// ---------------------------------------------------------------------------
__kernel void cnn2dDense_i128_o10(
    __global const float* input,
    __global const float* weights,
    __global const float* bias,
    __global float* output,
    const int activation,
    const int accumulate)
{
    const int o = get_global_id(0);
    if (o >= 10) return;

    float sum = 0.0f;
    for (int i = 0; i < 128; i++)
        sum += input[i] * weights[o * 128 + i];
    sum += bias[o];

    float value = sum;
    switch (activation)
    {
        case ReLU:    value = max(sum, 0.0f); break;
        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;
        case Tanh:    value = tanh(sum); break;
        case None:    value = sum; break;
    }

    output[o] = accumulate ? output[o] + value : value;
}
