#!/usr/bin/env python3

import argparse
import re
import sys
from pathlib import Path

KERNEL_FILE = Path(__file__).resolve().parent / "ccnKernel2d.cl"
C_HEADER_FILE = Path(__file__).resolve().parent / "kernelGen.h"
CORE_END_MARKER = "#endif // KERNELGEN_H"


def kernelName(width, height, channels, filterSize):
    return f"cnn2dFilter_w{width}_h{height}_c{channels}_f{filterSize}"


def offsetTerm(var, delta):
    if delta == 0:
        return var
    op = "+" if delta > 0 else "-"
    return f"({var} {op} {abs(delta)})"


def tapGuard(dy, dx, width, height):
    conds = []
    if dy < 0:
        conds.append(f"y >= {-dy}")
    elif dy > 0:
        conds.append(f"y < {height - dy}")
    if dx < 0:
        conds.append(f"x >= {-dx}")
    elif dx > 0:
        conds.append(f"x < {width - dx}")
    return " && ".join(conds)


def generateKernel(width, height, channels, filterSize):
    if min(width, height, channels, filterSize) < 1:
        raise ValueError("width, height, channels and filterSize must be >= 1")

    pad = filterSize // 2
    rowStride = width * channels
    planeStride = filterSize * channels
    name = kernelName(width, height, channels, filterSize)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {name} -- generated by generateKernel.py (kernelGen v2, do not edit by hand)")
    out.append(f"// width={width} height={height} channels={channels} filterSize={filterSize}")
    out.append("// params: input, filterWeights, filterBias, output, activation, accumulate")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"__kernel void {name}(")
    out.append("    __global const float* input,")
    out.append("    __global const float* filterWeights,")
    out.append("    const float filterBias,")
    out.append("    __global float* output,")
    out.append("    const int activation,")
    out.append("    const int accumulate)")
    out.append("{")
    out.append("    const int x = get_global_id(0);")
    out.append("    const int y = get_global_id(1);")
    out.append(f"    if (x >= {width} || y >= {height}) return;")
    out.append("")
    out.append("    float sum = 0.0f;")
    out.append("")

    for j in range(filterSize):
        dy = j - pad
        for i in range(filterSize):
            dx = i - pad
            base = f"base_{j}_{i}"
            guard = tapGuard(dy, dx, width, height)
            yTerm = offsetTerm("y", dy)
            xTerm = offsetTerm("x", dx)
            filterBase = j * planeStride + i * channels

            out.append(f"    // tap ({j}, {i})")
            inner = "    "
            if guard:
                out.append(f"    if ({guard})")
                out.append("    {")
                inner = "        "
            out.append(f"{inner}const int {base} = {yTerm} * {rowStride} + {xTerm} * {channels};")
            for k in range(channels):
                inIndex = f"[{base}]" if k == 0 else f"[{base} + {k}]"
                wIndex = f"[{filterBase}]" if k == 0 else f"[{filterBase + k}]"
                out.append(f"{inner}sum += input{inIndex} * filterWeights{wIndex};")
            if guard:
                out.append("    }")
            out.append("")

    out.append("    sum += filterBias;")
    out.append("")
    out.append("    float value = sum;")
    out.append("    switch (activation)")
    out.append("    {")
    out.append("        case ReLU:    value = max(sum, 0.0f); break;")
    out.append("        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;")
    out.append("        case Tanh:    value = tanh(sum); break;")
    out.append("        case None:    value = sum; break;")
    out.append("    }")
    out.append("")
    out.append(f"    const int idx = y * {width} + x;")
    out.append("    output[idx] = accumulate ? output[idx] + value : value;")
    out.append("}")
    return "\n".join(out) + "\n"


def cFunctionPrefix(width, height, channels, filterSize):
    return f"KGen_w{width}_h{height}_c{channels}_f{filterSize}"


def roundUp(value, multiple):
    return ((value + multiple - 1) // multiple) * multiple


def nextPow2(value):
    p = 1
    while p < value:
        p *= 2
    return p


def generateC(width, height, channels, filterSize):
    tag = f"W{width}_H{height}_C{channels}_F{filterSize}"
    pref = cFunctionPrefix(width, height, channels, filterSize)
    name = kernelName(width, height, channels, filterSize)
    gx = roundUp(width, 16)
    gy = roundUp(height, 16)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {pref} -- generated by generateKernel.py (do not edit by hand)")
    out.append(f"// kernel: {name}   width={width} height={height} channels={channels} filterSize={filterSize}")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"#define KGEN_{tag}_IN_FLOATS     ({width} * {height} * {channels})")
    out.append(f"#define KGEN_{tag}_OUT_FLOATS    ({width} * {height})")
    out.append(f"#define KGEN_{tag}_WEIGHT_FLOATS ({filterSize} * {filterSize} * {channels})")
    out.append("")
    out.append(f"static inline KGenConvLayer {pref}_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {{")
    out.append("\tKGenConvLayer layer = {0};")
    out.append(f"\tlayer.width = {width};")
    out.append(f"\tlayer.height = {height};")
    out.append(f"\tlayer.channels = {channels};")
    out.append(f"\tlayer.filterSize = {filterSize};")
    out.append("\tlayer.bias = bias;")
    out.append("\tlayer.localX = 16;")
    out.append("\tlayer.localY = 16;")
    out.append("")
    out.append(f'\tlayer.pip = CL_Pipeline_FromFile(ctx, clPath, "{name}", NULL);')
    out.append("\tif (layer.pip.kernel == NULL) {")
    out.append(f'\t\tprintf("[KGen] failed to build kernel {name} from %s\\n", clPath);')
    out.append("\t\treturn layer;")
    out.append("\t}")
    out.append("")
    out.append(f"\tlayer.hostWeights = malloc(KGEN_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\tif (layer.hostWeights == NULL) {")
    out.append('\t\tprintf("[KGen] weights allocation failed\\n");')
    out.append("\t\tCL_Pipeline_Destroy(&layer.pip);")
    out.append("\t\treturn layer;")
    out.append("\t}")
    out.append("\tif (weights != NULL) {")
    out.append(f"\t\tmemcpy(layer.hostWeights, weights, KGEN_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\t} else {")
    out.append(f"\t\tfor (int i = 0; i < KGEN_{tag}_WEIGHT_FLOATS; i++)")
    out.append("\t\t\tlayer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);")
    out.append("\t}")
    out.append(f"\tlayer.weights = CL_Buffer_CreateFromData(ctx, KGEN_{tag}_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);")
    out.append(f"\tlayer.inputBuf = CL_Buffer_Create(ctx, KGEN_{tag}_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);")
    out.append(f"\tlayer.outputBuf = CL_Buffer_Create(ctx, KGEN_{tag}_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);")
    out.append("\treturn layer;")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {{")
    out.append(f"\tmemcpy(layer->hostWeights, weights, KGEN_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\tlayer->bias = bias;")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {{")
    out.append(f"\tif (input->size < KGEN_{tag}_IN_FLOATS * sizeof(float) || output->size < KGEN_{tag}_OUT_FLOATS * sizeof(float)) {{")
    out.append(f'\t\tprintf("[KGen] buffer too small for {name}\\n");')
    out.append("\t\treturn;")
    out.append("\t}")
    out.append("\tCL_SetArgBuffer(&layer->pip, 0, input);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 1, &layer->weights);")
    out.append("\tCL_SetArgFloat(&layer->pip, 2, layer->bias);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 3, output);")
    out.append("\tCL_SetArgInt(&layer->pip, 4, activation);")
    out.append("\tCL_SetArgInt(&layer->pip, 5, accumulate);")
    out.append(f"\tCL_Dispatch2D(ctx, &layer->pip, {gx}, {gy}, layer->localX, layer->localY);")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {{")
    out.append("\tif (input == NULL || output == NULL) return;")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_{tag}_IN_FLOATS * sizeof(float));")
    out.append(f"\t{pref}_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);")
    out.append(f"\tCL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_{tag}_OUT_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {{")
    out.append(f"\tKGen_MutateWeights(layer->hostWeights, KGEN_{tag}_WEIGHT_FLOATS, amount);")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Destroy(KGenConvLayer *layer) {{")
    out.append("\tfree(layer->hostWeights);")
    out.append("\tCL_Buffer_Destroy(&layer->weights);")
    out.append("\tCL_Buffer_Destroy(&layer->inputBuf);")
    out.append("\tCL_Buffer_Destroy(&layer->outputBuf);")
    out.append("\tCL_Pipeline_Destroy(&layer->pip);")
    out.append("}")
    return "\n".join(out) + "\n"


def poolKernelName(width, height, channels, poolSize):
    return f"cnn2dMaxPool_w{width}_h{height}_c{channels}_p{poolSize}"


def poolCPrefix(width, height, channels, poolSize):
    return f"KGenPool_w{width}_h{height}_c{channels}_p{poolSize}"


def generateKernelPool(width, height, channels, poolSize):
    if min(width, height, channels, poolSize) < 1:
        raise ValueError("width, height, channels and poolSize must be >= 1")
    if width % poolSize != 0 or height % poolSize != 0:
        raise ValueError("width and height must be divisible by poolSize")

    outW = width // poolSize
    outH = height // poolSize
    name = poolKernelName(width, height, channels, poolSize)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {name} -- generated by generateKernel.py (do not edit by hand)")
    out.append(f"// width={width} height={height} channels={channels} poolSize={poolSize} -> {outW}x{outH}")
    out.append("// params: input, output")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"__kernel void {name}(")
    out.append("    __global const float* input,")
    out.append("    __global float* output)")
    out.append("{")
    out.append("    const int ox = get_global_id(0);")
    out.append("    const int oy = get_global_id(1);")
    out.append(f"    if (ox >= {outW} || oy >= {outH}) return;")
    out.append("")
    out.append(f"    const int base = ((oy * {poolSize}) * {width} + (ox * {poolSize})) * {channels};")
    out.append("")

    for c in range(channels):
        out.append(f"    // channel {c}")
        out.append(f"    float m{c} = -INFINITY;")
        for j in range(poolSize):
            for i in range(poolSize):
                offset = j * width * channels + i * channels + c
                index = "input[base]" if offset == 0 else f"input[base + {offset}]"
                out.append(f"    m{c} = max(m{c}, {index});")
        out.append(f"    output[(oy * {outW} + ox) * {channels} + {c}] = m{c};")
        out.append("")

    out.append("}")
    return "\n".join(out) + "\n"


def generateCPool(width, height, channels, poolSize):
    tag = f"W{width}_H{height}_C{channels}_P{poolSize}"
    pref = poolCPrefix(width, height, channels, poolSize)
    name = poolKernelName(width, height, channels, poolSize)
    outW = width // poolSize
    outH = height // poolSize
    gx = roundUp(outW, 16)
    gy = roundUp(outH, 16)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {pref} -- generated by generateKernel.py (do not edit by hand)")
    out.append(f"// kernel: {name}   width={width} height={height} channels={channels} poolSize={poolSize}")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"#define KGENPOOL_{tag}_IN_FLOATS  ({width} * {height} * {channels})")
    out.append(f"#define KGENPOOL_{tag}_OUT_FLOATS ({outW} * {outH} * {channels})")
    out.append("")
    out.append(f"static inline KGenPoolLayer {pref}_Init(CL_Context *ctx, const char *clPath) {{")
    out.append("\tKGenPoolLayer layer = {0};")
    out.append(f"\tlayer.width = {width};")
    out.append(f"\tlayer.height = {height};")
    out.append(f"\tlayer.channels = {channels};")
    out.append(f"\tlayer.poolSize = {poolSize};")
    out.append(f"\tlayer.outWidth = {outW};")
    out.append(f"\tlayer.outHeight = {outH};")
    out.append("\tlayer.localX = 16;")
    out.append("\tlayer.localY = 16;")
    out.append("")
    out.append(f'\tlayer.pip = CL_Pipeline_FromFile(ctx, clPath, "{name}", NULL);')
    out.append("\tif (layer.pip.kernel == NULL) {")
    out.append(f'\t\tprintf("[KGen] failed to build kernel {name} from %s\\n", clPath);')
    out.append("\t\treturn layer;")
    out.append("\t}")
    out.append("")
    out.append(f"\tlayer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_{tag}_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);")
    out.append(f"\tlayer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_{tag}_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);")
    out.append("\treturn layer;")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {{")
    out.append(f"\tif (input->size < KGENPOOL_{tag}_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_{tag}_OUT_FLOATS * sizeof(float)) {{")
    out.append(f'\t\tprintf("[KGen] buffer too small for {name}\\n");')
    out.append("\t\treturn;")
    out.append("\t}")
    out.append("\tCL_SetArgBuffer(&layer->pip, 0, input);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 1, output);")
    out.append(f"\tCL_Dispatch2D(ctx, &layer->pip, {gx}, {gy}, layer->localX, layer->localY);")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {{")
    out.append("\tif (input == NULL || output == NULL) return;")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_{tag}_IN_FLOATS * sizeof(float));")
    out.append(f"\t{pref}_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);")
    out.append(f"\tCL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_{tag}_OUT_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Destroy(KGenPoolLayer *layer) {{")
    out.append("\tCL_Buffer_Destroy(&layer->inputBuf);")
    out.append("\tCL_Buffer_Destroy(&layer->outputBuf);")
    out.append("\tCL_Pipeline_Destroy(&layer->pip);")
    out.append("}")
    return "\n".join(out) + "\n"


def denseKernelName(inputFloats, outputFloats):
    return f"cnn2dDense_i{inputFloats}_o{outputFloats}"


def denseCPrefix(inputFloats, outputFloats):
    return f"KGenDense_i{inputFloats}_o{outputFloats}"


def generateKernelDense(inputFloats, outputFloats):
    if min(inputFloats, outputFloats) < 1:
        raise ValueError("inputFloats and outputFloats must be >= 1")

    name = denseKernelName(inputFloats, outputFloats)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {name} -- generated by generateKernel.py (do not edit by hand)")
    out.append(f"// inputFloats={inputFloats} outputFloats={outputFloats}")
    out.append("// params: input, weights, bias, output, activation, accumulate")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"__kernel void {name}(")
    out.append("    __global const float* input,")
    out.append("    __global const float* weights,")
    out.append("    __global const float* bias,")
    out.append("    __global float* output,")
    out.append("    const int activation,")
    out.append("    const int accumulate)")
    out.append("{")
    out.append("    const int o = get_global_id(0);")
    out.append(f"    if (o >= {outputFloats}) return;")
    out.append("")
    out.append("    float sum = 0.0f;")
    out.append(f"    for (int i = 0; i < {inputFloats}; i++)")
    out.append(f"        sum += input[i] * weights[o * {inputFloats} + i];")
    out.append("    sum += bias[o];")
    out.append("")
    out.append("    float value = sum;")
    out.append("    switch (activation)")
    out.append("    {")
    out.append("        case ReLU:    value = max(sum, 0.0f); break;")
    out.append("        case Sigmoid: value = 1.0f / (1.0f + exp(-sum)); break;")
    out.append("        case Tanh:    value = tanh(sum); break;")
    out.append("        case None:    value = sum; break;")
    out.append("    }")
    out.append("")
    out.append("    output[o] = accumulate ? output[o] + value : value;")
    out.append("}")
    return "\n".join(out) + "\n"


def generateCDense(inputFloats, outputFloats):
    tag = f"I{inputFloats}_O{outputFloats}"
    pref = denseCPrefix(inputFloats, outputFloats)
    name = denseKernelName(inputFloats, outputFloats)
    localSize = min(64, nextPow2(outputFloats))
    gOut = roundUp(outputFloats, localSize)

    out = []
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"// {pref} -- generated by generateKernel.py (do not edit by hand)")
    out.append(f"// kernel: {name}   inputFloats={inputFloats} outputFloats={outputFloats}")
    out.append("// ---------------------------------------------------------------------------")
    out.append(f"#define KGENDENSE_{tag}_IN_FLOATS     ({inputFloats})")
    out.append(f"#define KGENDENSE_{tag}_OUT_FLOATS    ({outputFloats})")
    out.append(f"#define KGENDENSE_{tag}_WEIGHT_FLOATS ({outputFloats} * {inputFloats})")
    out.append(f"#define KGENDENSE_{tag}_BIAS_FLOATS   ({outputFloats})")
    out.append("")
    out.append(f"static inline KGenDenseLayer {pref}_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {{")
    out.append("\tKGenDenseLayer layer = {0};")
    out.append(f"\tlayer.inputFloats = {inputFloats};")
    out.append(f"\tlayer.outputFloats = {outputFloats};")
    out.append(f"\tlayer.local = {localSize};")
    out.append("")
    out.append(f'\tlayer.pip = CL_Pipeline_FromFile(ctx, clPath, "{name}", NULL);')
    out.append("\tif (layer.pip.kernel == NULL) {")
    out.append(f'\t\tprintf("[KGen] failed to build kernel {name} from %s\\n", clPath);')
    out.append("\t\treturn layer;")
    out.append("\t}")
    out.append("")
    out.append(f"\tlayer.hostWeights = malloc(KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\tif (layer.hostWeights == NULL) {")
    out.append('\t\tprintf("[KGen] weights allocation failed\\n");')
    out.append("\t\tCL_Pipeline_Destroy(&layer.pip);")
    out.append("\t\treturn layer;")
    out.append("\t}")
    out.append("\tif (weights != NULL) {")
    out.append(f"\t\tmemcpy(layer.hostWeights, weights, KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\t} else {")
    out.append(f"\t\tfor (int i = 0; i < KGENDENSE_{tag}_WEIGHT_FLOATS; i++)")
    out.append("\t\t\tlayer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);")
    out.append("\t}")
    out.append(f"\tlayer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);")
    out.append("")
    out.append("\tif (bias != NULL) {")
    out.append(f"\t\tlayer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_{tag}_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);")
    out.append("\t} else {")
    out.append(f"\t\tfloat *zeroBias = calloc(KGENDENSE_{tag}_BIAS_FLOATS, sizeof(float));")
    out.append(f"\t\tlayer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_{tag}_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);")
    out.append("\t\tfree(zeroBias);")
    out.append("\t}")
    out.append("")
    out.append(f"\tlayer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_{tag}_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);")
    out.append(f"\tlayer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_{tag}_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);")
    out.append("\treturn layer;")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {{")
    out.append(f"\tmemcpy(layer->hostWeights, weights, KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("\tif (bias != NULL)")
    out.append(f"\t\tCL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_{tag}_BIAS_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {{")
    out.append(f"\tif (input->size < KGENDENSE_{tag}_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_{tag}_OUT_FLOATS * sizeof(float)) {{")
    out.append(f'\t\tprintf("[KGen] buffer too small for {name}\\n");')
    out.append("\t\treturn;")
    out.append("\t}")
    out.append("\tCL_SetArgBuffer(&layer->pip, 0, input);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 1, &layer->weights);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 2, &layer->bias);")
    out.append("\tCL_SetArgBuffer(&layer->pip, 3, output);")
    out.append("\tCL_SetArgInt(&layer->pip, 4, activation);")
    out.append("\tCL_SetArgInt(&layer->pip, 5, accumulate);")
    out.append(f"\tCL_Dispatch1D(ctx, &layer->pip, {gOut}, layer->local);")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {{")
    out.append("\tif (input == NULL || output == NULL) return;")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_{tag}_IN_FLOATS * sizeof(float));")
    out.append(f"\t{pref}_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);")
    out.append(f"\tCL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_{tag}_OUT_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {{")
    out.append(f"\tKGen_MutateWeights(layer->hostWeights, KGENDENSE_{tag}_WEIGHT_FLOATS, amount);")
    out.append(f"\tCL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_{tag}_WEIGHT_FLOATS * sizeof(float));")
    out.append("}")
    out.append("")
    out.append(f"static inline void {pref}_Destroy(KGenDenseLayer *layer) {{")
    out.append("\tfree(layer->hostWeights);")
    out.append("\tCL_Buffer_Destroy(&layer->weights);")
    out.append("\tCL_Buffer_Destroy(&layer->bias);")
    out.append("\tCL_Buffer_Destroy(&layer->inputBuf);")
    out.append("\tCL_Buffer_Destroy(&layer->outputBuf);")
    out.append("\tCL_Pipeline_Destroy(&layer->pip);")
    out.append("}")
    return "\n".join(out) + "\n"


def appendC(path, anchor, source):
    if not path.exists():
        raise FileNotFoundError(f"C header not found: {path}")
    text = path.read_text()
    if re.search(rf"\b{re.escape(anchor)}\b", text):
        return False
    idx = text.rfind(CORE_END_MARKER)
    if idx == -1:
        raise ValueError(f"marker '{CORE_END_MARKER}' not found in {path}")
    path.write_text(text[:idx] + "\n" + source + "\n" + text[idx:])
    return True


def appendKernel(path, name, source):
    if not path.exists():
        raise FileNotFoundError(f"kernel file not found: {path}")
    text = path.read_text()
    if re.search(rf"\b{re.escape(name)}\b", text):
        return False
    with path.open("a") as fh:
        if text and not text.endswith("\n"):
            fh.write("\n")
        fh.write("\n" + source)
    return True


def promptInt(label, minimum=1):
    while True:
        raw = input(f"{label}: ").strip()
        try:
            value = int(raw)
        except ValueError:
            print("please enter an integer")
            continue
        if value < minimum:
            print(f"must be >= {minimum}")
            continue
        return value


def interactive():
    print("KernelGen interactive mode (press Ctrl+C to cancel)")
    mode = ""
    while mode not in ("conv", "pool", "dense"):
        mode = input("layer type (conv/pool/dense): ").strip().lower()
    if mode == "dense":
        inputFloats = promptInt("inputFloats")
        outputFloats = promptInt("outputFloats")
        return mode, (inputFloats, outputFloats)
    width = promptInt("width")
    height = promptInt("height")
    channels = promptInt("channels")
    if mode == "conv":
        return mode, (width, height, channels, promptInt("filterSize"))
    return mode, (width, height, channels, promptInt("poolSize"))


def emitConv(width, height, channels, filterSize):
    name = kernelName(width, height, channels, filterSize)
    if appendKernel(KERNEL_FILE, name, generateKernel(width, height, channels, filterSize)):
        print(f"appended {name} to {KERNEL_FILE}")
    else:
        print(f"{name} already exists in {KERNEL_FILE}, nothing to do")

    pref = cFunctionPrefix(width, height, channels, filterSize)
    if appendC(C_HEADER_FILE, f"{pref}_Init", generateC(width, height, channels, filterSize)):
        print(f"appended C helpers for {name} to {C_HEADER_FILE}")
    else:
        print(f"C helpers for {name} already exist in {C_HEADER_FILE}, nothing to do")


def emitPool(width, height, channels, poolSize):
    name = poolKernelName(width, height, channels, poolSize)
    if appendKernel(KERNEL_FILE, name, generateKernelPool(width, height, channels, poolSize)):
        print(f"appended {name} to {KERNEL_FILE}")
    else:
        print(f"{name} already exists in {KERNEL_FILE}, nothing to do")

    pref = poolCPrefix(width, height, channels, poolSize)
    if appendC(C_HEADER_FILE, f"{pref}_Init", generateCPool(width, height, channels, poolSize)):
        print(f"appended C helpers for {name} to {C_HEADER_FILE}")
    else:
        print(f"C helpers for {name} already exist in {C_HEADER_FILE}, nothing to do")


def emitDense(inputFloats, outputFloats):
    name = denseKernelName(inputFloats, outputFloats)
    if appendKernel(KERNEL_FILE, name, generateKernelDense(inputFloats, outputFloats)):
        print(f"appended {name} to {KERNEL_FILE}")
    else:
        print(f"{name} already exists in {KERNEL_FILE}, nothing to do")

    pref = denseCPrefix(inputFloats, outputFloats)
    if appendC(C_HEADER_FILE, f"{pref}_Init", generateCDense(inputFloats, outputFloats)):
        print(f"appended C helpers for {name} to {C_HEADER_FILE}")
    else:
        print(f"C helpers for {name} already exist in {C_HEADER_FILE}, nothing to do")


def main():
    argv = sys.argv[1:]
    if argv and argv[0].lstrip("+-").isdigit():
        argv = ["conv"] + argv

    if not argv:
        mode, params = interactive()
    else:
        parser = argparse.ArgumentParser(usage="%(prog)s conv|pool|dense ...")
        sub = parser.add_subparsers(dest="mode", required=True)

        p = sub.add_parser("conv", usage="%(prog)s conv width height channels filterSize")
        p.add_argument("width", type=int)
        p.add_argument("height", type=int)
        p.add_argument("channels", type=int)
        p.add_argument("filterSize", type=int)

        p = sub.add_parser("pool", usage="%(prog)s pool width height channels poolSize")
        p.add_argument("width", type=int)
        p.add_argument("height", type=int)
        p.add_argument("channels", type=int)
        p.add_argument("poolSize", type=int)

        p = sub.add_parser("dense", usage="%(prog)s dense inputFloats outputFloats")
        p.add_argument("inputFloats", type=int)
        p.add_argument("outputFloats", type=int)

        args = parser.parse_args(argv)
        if args.mode == "conv":
            params = (args.width, args.height, args.channels, args.filterSize)
        elif args.mode == "pool":
            params = (args.width, args.height, args.channels, args.poolSize)
        else:
            params = (args.inputFloats, args.outputFloats)
        mode = args.mode

    if mode == "conv":
        emitConv(*params)
    elif mode == "pool":
        emitPool(*params)
    else:
        emitDense(*params)


if __name__ == "__main__":
    main()
