#ifndef KERNELGEN_H
#define KERNELGEN_H

#include "../render/gpu/format.h" // CL_Context, CL_Pipeline, CL_Buffer, CL_SetArg*, CL_Dispatch2D

typedef enum { KGEN_RELU = 0, KGEN_SIGMOID = 1, KGEN_TANH = 2, KGEN_NONE = 3 } KGenActivation; // mirrors the enum in ccnKernel2d.cl

typedef struct {
	CL_Pipeline pip;
	CL_Buffer weights;    // F*F*C floats
	CL_Buffer inputBuf;   // scratch for the host-array _Run path
	CL_Buffer outputBuf;
	float *hostWeights;   // owned CPU copy, kept in sync by SetWeights/Mutate
	float bias;
	int width;
	int height;
	int channels;
	int filterSize;
	size_t localX;
	size_t localY;
} KGenConvLayer;

typedef struct {
	CL_Pipeline pip;
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	int width;
	int height;
	int channels;
	int poolSize;
	int outWidth;
	int outHeight;
	size_t localX;
	size_t localY;
} KGenPoolLayer;

typedef struct {
	CL_Pipeline pip;
	CL_Buffer weights;    // OUT*IN floats
	CL_Buffer bias;       // OUT floats
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	float *hostWeights;
	int inputFloats;
	int outputFloats;
	size_t local;
} KGenDenseLayer;

static inline void KGen_MutateWeights(float *weights, int count, float amount) {
	for (int i = 0; i < count; i++)
		weights[i] += amount * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
}


// ---------------------------------------------------------------------------
// KGen_w64_h64_c3_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w64_h64_c3_f3   width=64 height=64 channels=3 filterSize=3
// ---------------------------------------------------------------------------
#define KGEN_W64_H64_C3_F3_IN_FLOATS     (64 * 64 * 3)
#define KGEN_W64_H64_C3_F3_OUT_FLOATS    (64 * 64)
#define KGEN_W64_H64_C3_F3_WEIGHT_FLOATS (3 * 3 * 3)

static inline KGenConvLayer KGen_w64_h64_c3_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {
	KGenConvLayer layer = {0};
	layer.width = 64;
	layer.height = 64;
	layer.channels = 3;
	layer.filterSize = 3;
	layer.bias = bias;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w64_h64_c3_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w64_h64_c3_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W64_H64_C3_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);
	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGen_w64_h64_c3_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {
	memcpy(layer->hostWeights, weights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	layer->bias = bias;
}

static inline void KGen_w64_h64_c3_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w64_h64_c3_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgFloat(&layer->pip, 2, layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 64, 64, layer->localX, layer->localY);
}

static inline void KGen_w64_h64_c3_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float));
	KGen_w64_h64_c3_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float));
}

static inline void KGen_w64_h64_c3_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGen_w64_h64_c3_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c1_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c1_f3   width=28 height=28 channels=1 filterSize=3
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C1_F3_IN_FLOATS     (28 * 28 * 1)
#define KGEN_W28_H28_C1_F3_OUT_FLOATS    (28 * 28)
#define KGEN_W28_H28_C1_F3_WEIGHT_FLOATS (3 * 3 * 1)

static inline KGenConvLayer KGen_w28_h28_c1_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.bias = bias;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c1_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c1_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C1_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);
	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGen_w28_h28_c1_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	layer->bias = bias;
}

static inline void KGen_w28_h28_c1_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c1_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgFloat(&layer->pip, 2, layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

static inline void KGen_w28_h28_c1_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c1_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c1_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c1_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c1_p2   width=28 height=28 channels=1 poolSize=2
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C1_P2_IN_FLOATS  (28 * 28 * 1)
#define KGENPOOL_W28_H28_C1_P2_OUT_FLOATS (14 * 14 * 1)

static inline KGenPoolLayer KGenPool_w28_h28_c1_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.poolSize = 2;
	layer.outWidth = 14;
	layer.outHeight = 14;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c1_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c1_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGenPool_w28_h28_c1_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c1_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

static inline void KGenPool_w28_h28_c1_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c1_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float));
}

static inline void KGenPool_w28_h28_c1_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i196_o10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i196_o10   inputFloats=196 outputFloats=10
// ---------------------------------------------------------------------------
#define KGENDENSE_I196_O10_IN_FLOATS     (196)
#define KGENDENSE_I196_O10_OUT_FLOATS    (10)
#define KGENDENSE_I196_O10_WEIGHT_FLOATS (10 * 196)
#define KGENDENSE_I196_O10_BIAS_FLOATS   (10)

static inline KGenDenseLayer KGenDense_i196_o10_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 196;
	layer.outputFloats = 10;
	layer.local = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i196_o10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i196_o10 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I196_O10_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I196_O10_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I196_O10_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGenDense_i196_o10_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float));
}

static inline void KGenDense_i196_o10_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I196_O10_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i196_o10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 16, layer->local);
}

static inline void KGenDense_i196_o10_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I196_O10_IN_FLOATS * sizeof(float));
	KGenDense_i196_o10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float));
}

static inline void KGenDense_i196_o10_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGenDense_i196_o10_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c4_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c4_f3   width=28 height=28 channels=4 filterSize=3
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C4_F3_IN_FLOATS     (28 * 28 * 4)
#define KGEN_W28_H28_C4_F3_OUT_FLOATS    (28 * 28)
#define KGEN_W28_H28_C4_F3_WEIGHT_FLOATS (3 * 3 * 4)

static inline KGenConvLayer KGen_w28_h28_c4_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 4;
	layer.filterSize = 3;
	layer.bias = bias;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c4_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c4_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C4_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);
	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGen_w28_h28_c4_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	layer->bias = bias;
}

static inline void KGen_w28_h28_c4_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c4_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgFloat(&layer->pip, 2, layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

static inline void KGen_w28_h28_c4_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c4_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c4_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c4_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c8_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c8_f3   width=28 height=28 channels=8 filterSize=3
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C8_F3_IN_FLOATS     (28 * 28 * 8)
#define KGEN_W28_H28_C8_F3_OUT_FLOATS    (28 * 28)
#define KGEN_W28_H28_C8_F3_WEIGHT_FLOATS (3 * 3 * 8)

static inline KGenConvLayer KGen_w28_h28_c8_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 8;
	layer.filterSize = 3;
	layer.bias = bias;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c8_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c8_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C8_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);
	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGen_w28_h28_c8_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	layer->bias = bias;
}

static inline void KGen_w28_h28_c8_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c8_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgFloat(&layer->pip, 2, layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

static inline void KGen_w28_h28_c8_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c8_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c8_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGen_w28_h28_c8_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c8_p4 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c8_p4   width=28 height=28 channels=8 poolSize=4
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C8_P4_IN_FLOATS  (28 * 28 * 8)
#define KGENPOOL_W28_H28_C8_P4_OUT_FLOATS (7 * 7 * 8)

static inline KGenPoolLayer KGenPool_w28_h28_c8_p4_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 8;
	layer.poolSize = 4;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c8_p4", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c8_p4 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGenPool_w28_h28_c8_p4_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c8_p4\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

static inline void KGenPool_w28_h28_c8_p4_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c8_p4_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float));
}

static inline void KGenPool_w28_h28_c8_p4_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w14_h14_c1_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w14_h14_c1_f3   width=14 height=14 channels=1 filterSize=3
// ---------------------------------------------------------------------------
#define KGEN_W14_H14_C1_F3_IN_FLOATS     (14 * 14 * 1)
#define KGEN_W14_H14_C1_F3_OUT_FLOATS    (14 * 14)
#define KGEN_W14_H14_C1_F3_WEIGHT_FLOATS (3 * 3 * 1)

static inline KGenConvLayer KGen_w14_h14_c1_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, float bias) {
	KGenConvLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.bias = bias;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w14_h14_c1_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w14_h14_c1_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W14_H14_C1_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);
	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGen_w14_h14_c1_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, float bias) {
	memcpy(layer->hostWeights, weights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	layer->bias = bias;
}

static inline void KGen_w14_h14_c1_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w14_h14_c1_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgFloat(&layer->pip, 2, layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

static inline void KGen_w14_h14_c1_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float));
	KGen_w14_h14_c1_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float));
}

static inline void KGen_w14_h14_c1_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGen_w14_h14_c1_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w14_h14_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w14_h14_c1_p2   width=14 height=14 channels=1 poolSize=2
// ---------------------------------------------------------------------------
#define KGENPOOL_W14_H14_C1_P2_IN_FLOATS  (14 * 14 * 1)
#define KGENPOOL_W14_H14_C1_P2_OUT_FLOATS (7 * 7 * 1)

static inline KGenPoolLayer KGenPool_w14_h14_c1_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 1;
	layer.poolSize = 2;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w14_h14_c1_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w14_h14_c1_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGenPool_w14_h14_c1_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w14_h14_c1_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

static inline void KGenPool_w14_h14_c1_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float));
	KGenPool_w14_h14_c1_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float));
}

static inline void KGenPool_w14_h14_c1_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i49_o10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i49_o10   inputFloats=49 outputFloats=10
// ---------------------------------------------------------------------------
#define KGENDENSE_I49_O10_IN_FLOATS     (49)
#define KGENDENSE_I49_O10_OUT_FLOATS    (10)
#define KGENDENSE_I49_O10_WEIGHT_FLOATS (10 * 49)
#define KGENDENSE_I49_O10_BIAS_FLOATS   (10)

static inline KGenDenseLayer KGenDense_i49_o10_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 49;
	layer.outputFloats = 10;
	layer.local = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i49_o10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i49_o10 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I49_O10_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.2f * ((float)rand() / (float)RAND_MAX - 0.5f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I49_O10_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I49_O10_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

static inline void KGenDense_i49_o10_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float));
}

static inline void KGenDense_i49_o10_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I49_O10_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i49_o10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 16, layer->local);
}

static inline void KGenDense_i49_o10_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I49_O10_IN_FLOATS * sizeof(float));
	KGenDense_i49_o10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float));
}

static inline void KGenDense_i49_o10_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
}

static inline void KGenDense_i49_o10_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}

#endif // KERNELGEN_H
