#ifndef KERNELGEN_H
#define KERNELGEN_H

#include "../render/gpu/format.h" // CL_Context, CL_Pipeline, CL_Buffer, CL_SetArg*, CL_Dispatch2D

typedef enum { KGEN_RELU = 0, KGEN_SIGMOID = 1, KGEN_TANH = 2, KGEN_NONE = 3 } KGenActivation; // mirrors the enum in ccnKernel2d.cl

typedef struct {
	CL_Pipeline pip;
	CL_Buffer weights;    // N*F*F*C floats
	CL_Buffer inputBuf;   // scratch for the host-array _Run path
	CL_Buffer outputBuf;
	float *hostWeights;   // owned CPU copy, kept in sync by SetWeights/Mutate
	CL_Buffer bias;       // N floats (one per filter)
	int width;
	int height;
	int channels;
	int filterSize;
	size_t localX;
	size_t localY;
} KGenConvLayer;

typedef struct {
	CL_Pipeline pip;
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	int width;
	int height;
	int channels;
	int poolSize;
	int outWidth;
	int outHeight;
	size_t localX;
	size_t localY;
} KGenPoolLayer;

typedef struct {
	CL_Pipeline pip;
	CL_Buffer weights;    // OUT*IN floats
	CL_Buffer bias;       // OUT floats
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	float *hostWeights;
	int inputFloats;
	int outputFloats;
	size_t local;
} KGenDenseLayer;

typedef struct {
	CL_Pipeline pip;
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	int count;
} KGenSoftmaxLayer;

static inline void KGen_MutateWeights(float *weights, int count, float amount) {
	for (int i = 0; i < count; i++)
		weights[i] += amount * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
}


// ---------------------------------------------------------------------------
// KGen_w64_h64_c3_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w64_h64_c3_f3   width=64 height=64 channels=3 filterSize=3 filters=1
// dims: in 64x64x3 -> out 64x64x1 (output channels = 1) | weights [1][3][3][3] | bias [1]
// ---------------------------------------------------------------------------
#define KGEN_W64_H64_C3_F3_IN_FLOATS     (64 * 64 * 3)
#define KGEN_W64_H64_C3_F3_OUT_FLOATS    (64 * 64 * 1)
#define KGEN_W64_H64_C3_F3_WEIGHT_FLOATS (1 * 3 * 3 * 3)
#define KGEN_W64_H64_C3_F3_BIAS_FLOATS   (1)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w64_h64_c3_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 64;
	layer.height = 64;
	layer.channels = 3;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w64_h64_c3_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w64_h64_c3_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W64_H64_C3_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.471405f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W64_H64_C3_F3_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W64_H64_C3_F3_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W64_H64_C3_F3_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w64_h64_c3_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W64_H64_C3_F3_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w64_h64_c3_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w64_h64_c3_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 64, 64, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w64_h64_c3_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W64_H64_C3_F3_IN_FLOATS * sizeof(float));
	KGen_w64_h64_c3_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W64_H64_C3_F3_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w64_h64_c3_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W64_H64_C3_F3_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w64_h64_c3_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c1_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c1_f3   width=28 height=28 channels=1 filterSize=3 filters=1
// dims: in 28x28x1 -> out 28x28x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C1_F3_IN_FLOATS     (28 * 28 * 1)
#define KGEN_W28_H28_C1_F3_OUT_FLOATS    (28 * 28 * 1)
#define KGEN_W28_H28_C1_F3_WEIGHT_FLOATS (1 * 3 * 3 * 1)
#define KGEN_W28_H28_C1_F3_BIAS_FLOATS   (1)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w28_h28_c1_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c1_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c1_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C1_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.816497f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W28_H28_C1_F3_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w28_h28_c1_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W28_H28_C1_F3_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w28_h28_c1_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c1_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w28_h28_c1_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C1_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c1_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C1_F3_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w28_h28_c1_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w28_h28_c1_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c4_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c4_f3   width=28 height=28 channels=4 filterSize=3 filters=1
// dims: in 28x28x4 -> out 28x28x1 (output channels = 1) | weights [1][3][3][4] | bias [1]
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C4_F3_IN_FLOATS     (28 * 28 * 4)
#define KGEN_W28_H28_C4_F3_OUT_FLOATS    (28 * 28 * 1)
#define KGEN_W28_H28_C4_F3_WEIGHT_FLOATS (1 * 3 * 3 * 4)
#define KGEN_W28_H28_C4_F3_BIAS_FLOATS   (1)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w28_h28_c4_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 4;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c4_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c4_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C4_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.408248f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C4_F3_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W28_H28_C4_F3_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C4_F3_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w28_h28_c4_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W28_H28_C4_F3_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w28_h28_c4_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c4_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w28_h28_c4_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C4_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c4_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C4_F3_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w28_h28_c4_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C4_F3_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w28_h28_c4_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c8_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c8_f3   width=28 height=28 channels=8 filterSize=3 filters=1
// dims: in 28x28x8 -> out 28x28x1 (output channels = 1) | weights [1][3][3][8] | bias [1]
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C8_F3_IN_FLOATS     (28 * 28 * 8)
#define KGEN_W28_H28_C8_F3_OUT_FLOATS    (28 * 28 * 1)
#define KGEN_W28_H28_C8_F3_WEIGHT_FLOATS (1 * 3 * 3 * 8)
#define KGEN_W28_H28_C8_F3_BIAS_FLOATS   (1)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w28_h28_c8_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 8;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c8_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c8_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C8_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.288675f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C8_F3_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W28_H28_C8_F3_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C8_F3_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w28_h28_c8_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W28_H28_C8_F3_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w28_h28_c8_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c8_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w28_h28_c8_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C8_F3_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c8_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C8_F3_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w28_h28_c8_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C8_F3_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w28_h28_c8_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w14_h14_c1_f3 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w14_h14_c1_f3   width=14 height=14 channels=1 filterSize=3 filters=1
// dims: in 14x14x1 -> out 14x14x1 (output channels = 1) | weights [1][3][3][1] | bias [1]
// ---------------------------------------------------------------------------
#define KGEN_W14_H14_C1_F3_IN_FLOATS     (14 * 14 * 1)
#define KGEN_W14_H14_C1_F3_OUT_FLOATS    (14 * 14 * 1)
#define KGEN_W14_H14_C1_F3_WEIGHT_FLOATS (1 * 3 * 3 * 1)
#define KGEN_W14_H14_C1_F3_BIAS_FLOATS   (1)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w14_h14_c1_f3_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w14_h14_c1_f3", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w14_h14_c1_f3 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W14_H14_C1_F3_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.816497f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C1_F3_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W14_H14_C1_F3_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C1_F3_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w14_h14_c1_f3_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W14_H14_C1_F3_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w14_h14_c1_f3_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float) || output->size < KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w14_h14_c1_f3\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w14_h14_c1_f3_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W14_H14_C1_F3_IN_FLOATS * sizeof(float));
	KGen_w14_h14_c1_f3_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W14_H14_C1_F3_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w14_h14_c1_f3_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C1_F3_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w14_h14_c1_f3_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c1_f3_n4 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c1_f3_n4   width=28 height=28 channels=1 filterSize=3 filters=4
// dims: in 28x28x1 -> out 28x28x4 (output channels = 4) | weights [4][3][3][1] | bias [4]
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C1_F3_N4_IN_FLOATS     (28 * 28 * 1)
#define KGEN_W28_H28_C1_F3_N4_OUT_FLOATS    (28 * 28 * 4)
#define KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS (4 * 3 * 3 * 1)
#define KGEN_W28_H28_C1_F3_N4_BIAS_FLOATS   (4)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w28_h28_c1_f3_n4_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c1_f3_n4", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c1_f3_n4 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.816497f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N4_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W28_H28_C1_F3_N4_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N4_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_N4_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_N4_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w28_h28_c1_f3_n4_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W28_H28_C1_F3_N4_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w28_h28_c1_f3_n4_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C1_F3_N4_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C1_F3_N4_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c1_f3_n4\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w28_h28_c1_f3_n4_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C1_F3_N4_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c1_f3_n4_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C1_F3_N4_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w28_h28_c1_f3_n4_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_N4_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w28_h28_c1_f3_n4_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w14_h14_c4_f3_n4 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w14_h14_c4_f3_n4   width=14 height=14 channels=4 filterSize=3 filters=4
// dims: in 14x14x4 -> out 14x14x4 (output channels = 4) | weights [4][3][3][4] | bias [4]
// ---------------------------------------------------------------------------
#define KGEN_W14_H14_C4_F3_N4_IN_FLOATS     (14 * 14 * 4)
#define KGEN_W14_H14_C4_F3_N4_OUT_FLOATS    (14 * 14 * 4)
#define KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS (4 * 3 * 3 * 4)
#define KGEN_W14_H14_C4_F3_N4_BIAS_FLOATS   (4)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w14_h14_c4_f3_n4_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 4;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w14_h14_c4_f3_n4", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w14_h14_c4_f3_n4 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.408248f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C4_F3_N4_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W14_H14_C4_F3_N4_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C4_F3_N4_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C4_F3_N4_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C4_F3_N4_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w14_h14_c4_f3_n4_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W14_H14_C4_F3_N4_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w14_h14_c4_f3_n4_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W14_H14_C4_F3_N4_IN_FLOATS * sizeof(float) || output->size < KGEN_W14_H14_C4_F3_N4_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w14_h14_c4_f3_n4\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w14_h14_c4_f3_n4_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W14_H14_C4_F3_N4_IN_FLOATS * sizeof(float));
	KGen_w14_h14_c4_f3_n4_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W14_H14_C4_F3_N4_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w14_h14_c4_f3_n4_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C4_F3_N4_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w14_h14_c4_f3_n4_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c1_p2   width=28 height=28 channels=1 poolSize=2
// dims: in 28x28x1 -> out 14x14x1 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C1_P2_IN_FLOATS  (28 * 28 * 1)
#define KGENPOOL_W28_H28_C1_P2_OUT_FLOATS (14 * 14 * 1)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w28_h28_c1_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.poolSize = 2;
	layer.outWidth = 14;
	layer.outHeight = 14;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c1_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c1_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w28_h28_c1_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c1_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w28_h28_c1_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C1_P2_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c1_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C1_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w28_h28_c1_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c8_p4 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c8_p4   width=28 height=28 channels=8 poolSize=4
// dims: in 28x28x8 -> out 7x7x8 (max pool 4x4, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C8_P4_IN_FLOATS  (28 * 28 * 8)
#define KGENPOOL_W28_H28_C8_P4_OUT_FLOATS (7 * 7 * 8)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w28_h28_c8_p4_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 8;
	layer.poolSize = 4;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c8_p4", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c8_p4 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w28_h28_c8_p4_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c8_p4\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w28_h28_c8_p4_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C8_P4_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c8_p4_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C8_P4_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w28_h28_c8_p4_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w14_h14_c1_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w14_h14_c1_p2   width=14 height=14 channels=1 poolSize=2
// dims: in 14x14x1 -> out 7x7x1 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W14_H14_C1_P2_IN_FLOATS  (14 * 14 * 1)
#define KGENPOOL_W14_H14_C1_P2_OUT_FLOATS (7 * 7 * 1)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w14_h14_c1_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 1;
	layer.poolSize = 2;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w14_h14_c1_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w14_h14_c1_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w14_h14_c1_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w14_h14_c1_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w14_h14_c1_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W14_H14_C1_P2_IN_FLOATS * sizeof(float));
	KGenPool_w14_h14_c1_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W14_H14_C1_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w14_h14_c1_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c4_p2   width=28 height=28 channels=4 poolSize=2
// dims: in 28x28x4 -> out 14x14x4 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C4_P2_IN_FLOATS  (28 * 28 * 4)
#define KGENPOOL_W28_H28_C4_P2_OUT_FLOATS (14 * 14 * 4)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w28_h28_c4_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 4;
	layer.poolSize = 2;
	layer.outWidth = 14;
	layer.outHeight = 14;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c4_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c4_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C4_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C4_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w28_h28_c4_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C4_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C4_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c4_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w28_h28_c4_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C4_P2_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c4_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C4_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w28_h28_c4_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w14_h14_c4_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w14_h14_c4_p2   width=14 height=14 channels=4 poolSize=2
// dims: in 14x14x4 -> out 7x7x4 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W14_H14_C4_P2_IN_FLOATS  (14 * 14 * 4)
#define KGENPOOL_W14_H14_C4_P2_OUT_FLOATS (7 * 7 * 4)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w14_h14_c4_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 4;
	layer.poolSize = 2;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w14_h14_c4_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w14_h14_c4_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C4_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C4_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w14_h14_c4_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W14_H14_C4_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W14_H14_C4_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w14_h14_c4_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w14_h14_c4_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W14_H14_C4_P2_IN_FLOATS * sizeof(float));
	KGenPool_w14_h14_c4_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W14_H14_C4_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w14_h14_c4_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i196_o10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i196_o10   inputFloats=196 outputFloats=10
// dims: in 196 -> out 10 | weights [10][196] | bias [10]
// ---------------------------------------------------------------------------
#define KGENDENSE_I196_O10_IN_FLOATS     (196)
#define KGENDENSE_I196_O10_OUT_FLOATS    (10)
#define KGENDENSE_I196_O10_WEIGHT_FLOATS (10 * 196)
#define KGENDENSE_I196_O10_BIAS_FLOATS   (10)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenDenseLayer KGenDense_i196_o10_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 196;
	layer.outputFloats = 10;
	layer.local = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i196_o10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i196_o10 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I196_O10_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.174964f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I196_O10_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I196_O10_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGenDense_i196_o10_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I196_O10_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenDense_i196_o10_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I196_O10_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i196_o10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 16, layer->local);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenDense_i196_o10_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I196_O10_IN_FLOATS * sizeof(float));
	KGenDense_i196_o10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I196_O10_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGenDense_i196_o10_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I196_O10_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGenDense_i196_o10_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i49_o10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i49_o10   inputFloats=49 outputFloats=10
// dims: in 49 -> out 10 | weights [10][49] | bias [10]
// ---------------------------------------------------------------------------
#define KGENDENSE_I49_O10_IN_FLOATS     (49)
#define KGENDENSE_I49_O10_OUT_FLOATS    (10)
#define KGENDENSE_I49_O10_WEIGHT_FLOATS (10 * 49)
#define KGENDENSE_I49_O10_BIAS_FLOATS   (10)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenDenseLayer KGenDense_i49_o10_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 49;
	layer.outputFloats = 10;
	layer.local = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i49_o10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i49_o10 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I49_O10_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.349927f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I49_O10_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I49_O10_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGenDense_i49_o10_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I49_O10_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenDense_i49_o10_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I49_O10_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i49_o10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 16, layer->local);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenDense_i49_o10_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I49_O10_IN_FLOATS * sizeof(float));
	KGenDense_i49_o10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I49_O10_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGenDense_i49_o10_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I49_O10_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGenDense_i49_o10_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenSoftmax_n10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dSoftmax_n10   count=10
// dims: in 10 -> out 10 (softmax, sums to 1)
// ---------------------------------------------------------------------------
#define KGENSOFTMAX_N10_COUNT (10)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenSoftmaxLayer KGenSoftmax_n10_Init(CL_Context *ctx, const char *clPath) {
	KGenSoftmaxLayer layer = {0};
	layer.count = 10;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dSoftmax_n10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dSoftmax_n10 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENSOFTMAX_N10_COUNT * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENSOFTMAX_N10_COUNT * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (single work-item)
static inline void KGenSoftmax_n10_Forward(CL_Context *ctx, KGenSoftmaxLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENSOFTMAX_N10_COUNT * sizeof(float) || output->size < KGENSOFTMAX_N10_COUNT * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dSoftmax_n10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch1D(ctx, &layer->pip, 1, 1);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenSoftmax_n10_Run(CL_Context *ctx, KGenSoftmaxLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENSOFTMAX_N10_COUNT * sizeof(float));
	KGenSoftmax_n10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENSOFTMAX_N10_COUNT * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenSoftmax_n10_Destroy(KGenSoftmaxLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w28_h28_c1_f3_n16 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w28_h28_c1_f3_n16   width=28 height=28 channels=1 filterSize=3 filters=16
// dims: in 28x28x1 -> out 28x28x16 (output channels = 16) | weights [16][3][3][1] | bias [16]
// ---------------------------------------------------------------------------
#define KGEN_W28_H28_C1_F3_N16_IN_FLOATS     (28 * 28 * 1)
#define KGEN_W28_H28_C1_F3_N16_OUT_FLOATS    (28 * 28 * 16)
#define KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS (16 * 3 * 3 * 1)
#define KGEN_W28_H28_C1_F3_N16_BIAS_FLOATS   (16)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w28_h28_c1_f3_n16_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 1;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w28_h28_c1_f3_n16", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w28_h28_c1_f3_n16 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.816497f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N16_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W28_H28_C1_F3_N16_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W28_H28_C1_F3_N16_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_N16_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W28_H28_C1_F3_N16_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w28_h28_c1_f3_n16_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W28_H28_C1_F3_N16_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w28_h28_c1_f3_n16_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W28_H28_C1_F3_N16_IN_FLOATS * sizeof(float) || output->size < KGEN_W28_H28_C1_F3_N16_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w28_h28_c1_f3_n16\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w28_h28_c1_f3_n16_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W28_H28_C1_F3_N16_IN_FLOATS * sizeof(float));
	KGen_w28_h28_c1_f3_n16_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W28_H28_C1_F3_N16_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w28_h28_c1_f3_n16_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W28_H28_C1_F3_N16_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w28_h28_c1_f3_n16_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w28_h28_c16_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w28_h28_c16_p2   width=28 height=28 channels=16 poolSize=2
// dims: in 28x28x16 -> out 14x14x16 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W28_H28_C16_P2_IN_FLOATS  (28 * 28 * 16)
#define KGENPOOL_W28_H28_C16_P2_OUT_FLOATS (14 * 14 * 16)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w28_h28_c16_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 28;
	layer.height = 28;
	layer.channels = 16;
	layer.poolSize = 2;
	layer.outWidth = 14;
	layer.outHeight = 14;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w28_h28_c16_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w28_h28_c16_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C16_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W28_H28_C16_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w28_h28_c16_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W28_H28_C16_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W28_H28_C16_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w28_h28_c16_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w28_h28_c16_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W28_H28_C16_P2_IN_FLOATS * sizeof(float));
	KGenPool_w28_h28_c16_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W28_H28_C16_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w28_h28_c16_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGen_w14_h14_c16_f3_n32 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dFilter_w14_h14_c16_f3_n32   width=14 height=14 channels=16 filterSize=3 filters=32
// dims: in 14x14x16 -> out 14x14x32 (output channels = 32) | weights [32][3][3][16] | bias [32]
// ---------------------------------------------------------------------------
#define KGEN_W14_H14_C16_F3_N32_IN_FLOATS     (14 * 14 * 16)
#define KGEN_W14_H14_C16_F3_N32_OUT_FLOATS    (14 * 14 * 32)
#define KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS (32 * 3 * 3 * 16)
#define KGEN_W14_H14_C16_F3_N32_BIAS_FLOATS   (32)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenConvLayer KGen_w14_h14_c16_f3_n32_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenConvLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 16;
	layer.filterSize = 3;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dFilter_w14_h14_c16_f3_n32", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dFilter_w14_h14_c16_f3_n32 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.204124f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C16_F3_N32_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGEN_W14_H14_C16_F3_N32_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGEN_W14_H14_C16_F3_N32_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C16_F3_N32_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGEN_W14_H14_C16_F3_N32_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGen_w14_h14_c16_f3_n32_SetWeights(CL_Context *ctx, KGenConvLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGEN_W14_H14_C16_F3_N32_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGen_w14_h14_c16_f3_n32_Forward(CL_Context *ctx, KGenConvLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGEN_W14_H14_C16_F3_N32_IN_FLOATS * sizeof(float) || output->size < KGEN_W14_H14_C16_F3_N32_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dFilter_w14_h14_c16_f3_n32\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGen_w14_h14_c16_f3_n32_Run(CL_Context *ctx, KGenConvLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGEN_W14_H14_C16_F3_N32_IN_FLOATS * sizeof(float));
	KGen_w14_h14_c16_f3_n32_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGEN_W14_H14_C16_F3_N32_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGen_w14_h14_c16_f3_n32_Mutate(CL_Context *ctx, KGenConvLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGEN_W14_H14_C16_F3_N32_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGen_w14_h14_c16_f3_n32_Destroy(KGenConvLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPool_w14_h14_c32_p2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dMaxPool_w14_h14_c32_p2   width=14 height=14 channels=32 poolSize=2
// dims: in 14x14x32 -> out 7x7x32 (max pool 2x2, per channel)
// ---------------------------------------------------------------------------
#define KGENPOOL_W14_H14_C32_P2_IN_FLOATS  (14 * 14 * 32)
#define KGENPOOL_W14_H14_C32_P2_OUT_FLOATS (7 * 7 * 32)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPoolLayer KGenPool_w14_h14_c32_p2_Init(CL_Context *ctx, const char *clPath) {
	KGenPoolLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 32;
	layer.poolSize = 2;
	layer.outWidth = 7;
	layer.outHeight = 7;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dMaxPool_w14_h14_c32_p2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dMaxPool_w14_h14_c32_p2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C32_P2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPOOL_W14_H14_C32_P2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPool_w14_h14_c32_p2_Forward(CL_Context *ctx, KGenPoolLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPOOL_W14_H14_C32_P2_IN_FLOATS * sizeof(float) || output->size < KGENPOOL_W14_H14_C32_P2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dMaxPool_w14_h14_c32_p2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 16, 16, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPool_w14_h14_c32_p2_Run(CL_Context *ctx, KGenPoolLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPOOL_W14_H14_C32_P2_IN_FLOATS * sizeof(float));
	KGenPool_w14_h14_c32_p2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPOOL_W14_H14_C32_P2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPool_w14_h14_c32_p2_Destroy(KGenPoolLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i1568_o128 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i1568_o128   inputFloats=1568 outputFloats=128
// dims: in 1568 -> out 128 | weights [128][1568] | bias [128]
// ---------------------------------------------------------------------------
#define KGENDENSE_I1568_O128_IN_FLOATS     (1568)
#define KGENDENSE_I1568_O128_OUT_FLOATS    (128)
#define KGENDENSE_I1568_O128_WEIGHT_FLOATS (128 * 1568)
#define KGENDENSE_I1568_O128_BIAS_FLOATS   (128)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenDenseLayer KGenDense_i1568_o128_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 1568;
	layer.outputFloats = 128;
	layer.local = 64;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i1568_o128", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i1568_o128 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I1568_O128_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.061859f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I1568_O128_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I1568_O128_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I1568_O128_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I1568_O128_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I1568_O128_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGenDense_i1568_o128_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I1568_O128_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenDense_i1568_o128_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I1568_O128_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I1568_O128_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i1568_o128\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 128, layer->local);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenDense_i1568_o128_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I1568_O128_IN_FLOATS * sizeof(float));
	KGenDense_i1568_o128_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I1568_O128_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGenDense_i1568_o128_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I1568_O128_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I1568_O128_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGenDense_i1568_o128_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenDense_i128_o10 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dDense_i128_o10   inputFloats=128 outputFloats=10
// dims: in 128 -> out 10 | weights [10][128] | bias [10]
// ---------------------------------------------------------------------------
#define KGENDENSE_I128_O10_IN_FLOATS     (128)
#define KGENDENSE_I128_O10_OUT_FLOATS    (10)
#define KGENDENSE_I128_O10_WEIGHT_FLOATS (10 * 128)
#define KGENDENSE_I128_O10_BIAS_FLOATS   (10)

// Init: builds the kernel; weights NULL = random (kaiming-uniform), bias NULL = zeros; allocates the buffers
static inline KGenDenseLayer KGenDense_i128_o10_Init(CL_Context *ctx, const char *clPath, const float *weights, const float *bias) {
	KGenDenseLayer layer = {0};
	layer.inputFloats = 128;
	layer.outputFloats = 10;
	layer.local = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dDense_i128_o10", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dDense_i128_o10 from %s\n", clPath);
		return layer;
	}

	layer.hostWeights = malloc(KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float));
	if (layer.hostWeights == NULL) {
		printf("[KGen] weights allocation failed\n");
		CL_Pipeline_Destroy(&layer.pip);
		return layer;
	}
	if (weights != NULL) {
		memcpy(layer.hostWeights, weights, KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float));
	} else {
		for (int i = 0; i < KGENDENSE_I128_O10_WEIGHT_FLOATS; i++)
			layer.hostWeights[i] = 0.216506f * (2.0f * ((float)rand() / (float)RAND_MAX) - 1.0f);
	}
	layer.weights = CL_Buffer_CreateFromData(ctx, KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float), (void *)layer.hostWeights, CL_MEM_READ_ONLY);

	if (bias != NULL) {
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I128_O10_BIAS_FLOATS * sizeof(float), (void *)bias, CL_MEM_READ_ONLY);
	} else {
		float *zeroBias = calloc(KGENDENSE_I128_O10_BIAS_FLOATS, sizeof(float));
		layer.bias = CL_Buffer_CreateFromData(ctx, KGENDENSE_I128_O10_BIAS_FLOATS * sizeof(float), (void *)zeroBias, CL_MEM_READ_ONLY);
		free(zeroBias);
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENDENSE_I128_O10_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENDENSE_I128_O10_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// SetWeights: uploads weights (and bias when not NULL)
static inline void KGenDense_i128_o10_SetWeights(CL_Context *ctx, KGenDenseLayer *layer, const float *weights, const float *bias) {
	memcpy(layer->hostWeights, weights, KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float));
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float));
	if (bias != NULL)
		CL_Buffer_Write(ctx, &layer->bias, (void *)bias, KGENDENSE_I128_O10_BIAS_FLOATS * sizeof(float));
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenDense_i128_o10_Forward(CL_Context *ctx, KGenDenseLayer *layer, CL_Buffer *input, CL_Buffer *output, int activation, int accumulate) {
	if (input->size < KGENDENSE_I128_O10_IN_FLOATS * sizeof(float) || output->size < KGENDENSE_I128_O10_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dDense_i128_o10\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, &layer->weights);
	CL_SetArgBuffer(&layer->pip, 2, &layer->bias);
	CL_SetArgBuffer(&layer->pip, 3, output);
	CL_SetArgInt(&layer->pip, 4, activation);
	CL_SetArgInt(&layer->pip, 5, accumulate);
	CL_Dispatch1D(ctx, &layer->pip, 16, layer->local);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenDense_i128_o10_Run(CL_Context *ctx, KGenDenseLayer *layer, const float *input, float *output, int activation, int accumulate) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENDENSE_I128_O10_IN_FLOATS * sizeof(float));
	KGenDense_i128_o10_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf, activation, accumulate);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENDENSE_I128_O10_OUT_FLOATS * sizeof(float));
}

// Mutate: hostWeights += amount * U[-1, 1], then re-uploads
static inline void KGenDense_i128_o10_Mutate(CL_Context *ctx, KGenDenseLayer *layer, float amount) {
	KGen_MutateWeights(layer->hostWeights, KGENDENSE_I128_O10_WEIGHT_FLOATS, amount);
	CL_Buffer_Write(ctx, &layer->weights, (void *)layer->hostWeights, KGENDENSE_I128_O10_WEIGHT_FLOATS * sizeof(float));
}

// Destroy: releases hostWeights, GPU buffers and the pipeline
static inline void KGenDense_i128_o10_Destroy(KGenDenseLayer *layer) {
	free(layer->hostWeights);
	CL_Buffer_Destroy(&layer->weights);
	CL_Buffer_Destroy(&layer->bias);
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}


// ---------------------------------------------------------------------------
// KGenPixelShuffle_w14_h14_c1_r2 -- generated by generateKernel.py (do not edit by hand)
// kernel: cnn2dPixelShuffle_w14_h14_c1_r2   width=14 height=14 channels=1 upscale=2
// dims: in 14x14x4 -> out 28x28x1 (pixel shuffle x2, channels-last)
// ---------------------------------------------------------------------------
// Guarded: the struct is also in the skeleton preamble, and this block may be
// appended to a header that already has it.
#ifndef KGEN_PIXELSHUFFLE_LAYER_DEFINED
#define KGEN_PIXELSHUFFLE_LAYER_DEFINED
typedef struct {
	CL_Pipeline pip;
	CL_Buffer inputBuf;
	CL_Buffer outputBuf;
	int width;        // input width (output width = width * upscale)
	int height;       // input height (output height = height * upscale)
	int channels;     // output channels (input channels = channels * upscale^2)
	int upscale;
	int outWidth;
	int outHeight;
	size_t localX;
	size_t localY;
} KGenPixelShuffleLayer;
#endif

#define KGENPIXELSHUFFLE_W14_H14_C1_R2_IN_FLOATS  (14 * 14 * 4)
#define KGENPIXELSHUFFLE_W14_H14_C1_R2_OUT_FLOATS (28 * 28 * 1)

// Init: builds the kernel and the scratch buffers (no weights)
static inline KGenPixelShuffleLayer KGenPixelShuffle_w14_h14_c1_r2_Init(CL_Context *ctx, const char *clPath) {
	KGenPixelShuffleLayer layer = {0};
	layer.width = 14;
	layer.height = 14;
	layer.channels = 1;
	layer.upscale = 2;
	layer.outWidth = 28;
	layer.outHeight = 28;
	layer.localX = 16;
	layer.localY = 16;

	layer.pip = CL_Pipeline_FromFile(ctx, clPath, "cnn2dPixelShuffle_w14_h14_c1_r2", NULL);
	if (layer.pip.kernel == NULL) {
		printf("[KGen] failed to build kernel cnn2dPixelShuffle_w14_h14_c1_r2 from %s\n", clPath);
		return layer;
	}

	layer.inputBuf = CL_Buffer_Create(ctx, KGENPIXELSHUFFLE_W14_H14_C1_R2_IN_FLOATS * sizeof(float), CL_MEM_READ_ONLY);
	layer.outputBuf = CL_Buffer_Create(ctx, KGENPIXELSHUFFLE_W14_H14_C1_R2_OUT_FLOATS * sizeof(float), CL_MEM_READ_WRITE);
	return layer;
}

// Forward: dispatches on CL buffers (zero-copy chaining)
static inline void KGenPixelShuffle_w14_h14_c1_r2_Forward(CL_Context *ctx, KGenPixelShuffleLayer *layer, CL_Buffer *input, CL_Buffer *output) {
	if (input->size < KGENPIXELSHUFFLE_W14_H14_C1_R2_IN_FLOATS * sizeof(float) || output->size < KGENPIXELSHUFFLE_W14_H14_C1_R2_OUT_FLOATS * sizeof(float)) {
		printf("[KGen] buffer too small for cnn2dPixelShuffle_w14_h14_c1_r2\n");
		return;
	}
	CL_SetArgBuffer(&layer->pip, 0, input);
	CL_SetArgBuffer(&layer->pip, 1, output);
	CL_Dispatch2D(ctx, &layer->pip, 32, 32, layer->localX, layer->localY);
}

// Run: host input -> scratch buffers -> Forward -> host output
static inline void KGenPixelShuffle_w14_h14_c1_r2_Run(CL_Context *ctx, KGenPixelShuffleLayer *layer, const float *input, float *output) {
	if (input == NULL || output == NULL) return;
	CL_Buffer_Write(ctx, &layer->inputBuf, (void *)input, KGENPIXELSHUFFLE_W14_H14_C1_R2_IN_FLOATS * sizeof(float));
	KGenPixelShuffle_w14_h14_c1_r2_Forward(ctx, layer, &layer->inputBuf, &layer->outputBuf);
	CL_Buffer_Read(ctx, &layer->outputBuf, output, KGENPIXELSHUFFLE_W14_H14_C1_R2_OUT_FLOATS * sizeof(float));
}

// Destroy: releases GPU buffers and the pipeline
static inline void KGenPixelShuffle_w14_h14_c1_r2_Destroy(KGenPixelShuffleLayer *layer) {
	CL_Buffer_Destroy(&layer->inputBuf);
	CL_Buffer_Destroy(&layer->outputBuf);
	CL_Pipeline_Destroy(&layer->pip);
}

#endif // KERNELGEN_H
