_wandb:
    value:
        cli_version: 0.25.1
        e:
            dvqup9z09nhrtshb2pdc0cvpehox5ly9:
                codePath: simulation/wandb_logger.py
                codePathLocal: wandb_logger.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "243885932544"
                        used: "169054625792"
                email: matus.benky@gmail.com
                executable: /home/user/anaconda3/bin/python
                git:
                    commit: cb45e7a2aa726195f1dfef65d5283136fae07f9d
                    remote: git@github.com:DarkBenky/gengin.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-4719cf90-a4e4-4859-2e53-bfd7c9dcd8aa
                host: user-System-Product-Name
                memory:
                    total: "134971289600"
                os: Linux-6.17.0-22-generic-x86_64-with-glibc2.39
                program: /home/user/Desktop/gengin/simulation/wandb_logger.py
                python: CPython 3.13.9
                root: /home/user/Desktop/gengin/simulation
                startedAt: "2026-04-28T22:22:35.298649Z"
                writerId: dvqup9z09nhrtshb2pdc0cvpehox5ly9
        m: []
        python_version: 3.13.9
        t:
            "3":
                - 2
                - 61
            "4": 3.13.9
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
